### ISSUE TITLE
Improvement: Organization with multiple locations

### ISSUE THREAD

**Issue by macmon-secure** [onelogin/java-saml#102]
When i create SP Metadata from the Saml2Settings it's hardcoded in the Metadata class, that the organization will get the language "en". 

`valueMap.put("strOrganization", toOrganizationXml(settings.getOrganization(), "en"));`

In onelogin/php-saml it's possible to add information for multiple locations, like "en-US", "de-DE" and so on.

**Comment by pitbulk** [comment]
Yes, you can see that the [toOrganizationXml](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/Metadata.java#L279) supports lang, but the [generateSubstitutor](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/Metadata.java#L155) method uses always "en".

I think we should define at the [settings](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties#L150) a onelogin.saml2.organization.lang and provide a getOrganizationLang method on [Saml2Settings.java](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java) to be used instead the hardcoded lang.

Are you able to provide a PR?

**Comment by cgroix** [comment]
I am using your library to implement SAML on our software and a customer asks us to change the lang attribute.
Would you be interested in a simple PR with the `onelogin.saml2.organization.lang` setting ?

**Comment by pitbulk** [comment]
Ok
