### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by benmccann** [onelogin/java-saml#12]
It would be easier to integrate into our product if the library were published to Maven Central. This would also solve other problems such as automatically pulling in the required dependencies such as Apache Commons Codec and whatever else is needed.

**Comment by smchristensen** [comment]
Any update on this?

**Comment by dlevis** [comment]
We would need this too. When can we expect the libraries to be in Maven Central?

**Comment by pitbulk** [comment]
The toolkit is still under development, we plan to publish it at the end o this month.

**Comment by mdavidn** [comment]
Looked for this on Maven Central this week and did not find it.

**Comment by smchristensen** [comment]
If you are looking for people to integrate their applications with your services, it would behoove you to make it as easy as possible.  I have been waiting on this for well over a year now.  Publishing the build is not that difficult to do and something that would have a positive direct impact on your customers.  October 16, 2015 was the last update from OneLogin and the "end of the month" has come and gone many end-of-the-months ago.  Can we have someone please give us a better concrete timeline for when this will be complete?

**Comment by pitbulk** [comment]
Not published yet. I'm adding unit test for all the methods and need to write documentation.

For those users that used the [2.0.0 version](https://github.com/onelogin/java-saml/tree/v2.0.0)
Does anyone be able to contribute with the project describing the steps they followed to include the library on their project/IDE?

**Comment by pitbulk** [comment]
Anyone with some spare time to contribute on releasing the new java-saml toolkit?
The code is ready and I implemented a big bunch of unit test to ensure all is working as expected, but I'm not a Java expert so some help with documentation, testing (install and try the toolkit) and guide how prepare the toolkit to be published in maven is very welcome!

@benmccann?

**Comment by benmccann** [comment]
I ended up using pac4j-saml, so I'm afraid I can't help on this one

**Comment by miszobi** [comment]
@pitbulk I can help preparing the project for releasing to maven central, and prepare a short guide for doing the actual release. To clarify, would you like to release from the v2.0.0 branch, or from the v1.1.2/master branch (actually what's the difference between the two? Both seem to have the 1.1.2 version)?

For releasing the easiest way to go is to use the [Sonatype OSS Repository Hosting](http://central.sonatype.org/pages/ossrh-guide.html). You'll want to follow the linked guide to create a JIRA account, and create a New Project ticket, to claim the 'com.onelogin' groupid, so later on you can use it to publish the project to maven central.

**Comment by pitbulk** [comment]
Hi @miszobi 

thanks for the info and for your proposal.

I want to release the v2.0.0 branch (it has a lot of security improvements that aren't in 1.1.2).
I sent the info to my manager to validate the process that you suggester 

P.S I will send a push a big PR with more improvements and unit test for the v2.0.0 this week.

**Comment by luuuis** [comment]
I am watching this with interest. I agree that going the Sonatype OSS route is the easiest/best way to go about it, also happy to help where possible.

**Comment by RockyMM** [comment]
People with far more knowledge than me already have responded, but still I would like to help wherever I can.

**Comment by pitbulk** [comment]
Ok, thanks for the support. I pushed all the code on the [v2.0.0](https://github.com/onelogin/java-saml/tree/v2.0.0) branch.

I think first step is to install manually, configure and test if you experience any issue with the toolkit.

I created this meta-ticket with the pending tasks: https://github.com/onelogin/java-saml/issues/50
