### ISSUE TITLE
error: package ... is not visible

### ISSUE THREAD

**Issue by Dmole** [onelogin/java-saml#121]
Please support the use of Java 9 modules by doing something about `com.sun.org.apache.xml.internal.security`.

Options:
- use javax.xml.crypto etc or some other implementation
- use a 392K compatibility JAR from JRE8;
7z x rt.jar com/sun/org/apache/xml/internal/security
7z a -tzip com.sun.org.apache.xml.internal.security.jar com
- find some argument to pass to javac to expose it
`--add-modules com.sun.org.apache.xml.internal.security` or `requires com.sun.org.apache.xml.internal.security;`

**Comment by pitbulk** [comment]
Where is a com.sun.* package used?
We using [org.apache.xml.security](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java#L59)

**Comment by Dmole** [comment]
Ah sorry It was org.apache.xml.security but while refactoring to solve https://github.com/onelogin/java-saml/issues/113 I let the former sneak in.
