### ISSUE TITLE
LogoutRequest wrong nameId?

### ISSUE THREAD

**Issue by Loki-Afro** [onelogin/java-saml#123]
Hi there,

I'm new to saml so bar with me ;)

```
<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_1eba4c60-5f35-49a2-98cf-d29e64f295c3" Version="2.0" IssueInstant="2017-09-20T15:20:49Z" Destination="https://idp.ssocircle.com:443/sso/IDPSloRedirect/metaAlias/publicidp" >

<saml:Issuer>superFancySp2</saml:Issuer>

<saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" SPNameQualifier="superFancySp2">https://idp.ssocircle.com</saml:NameID>

</samlp:LogoutRequest>
```

Isn't the value of `saml:NameID` wrong here? Shouldn't it be something sp-related?

**Comment by pitbulk** [comment]
You are sending a LogoutRequest to the IdP SLS endpoint https://idp.ssocircle.com:443/sso/IDPSloRedirect/metaAlias/publicidp

To the [logout](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L363) method, you can provide nameId and nameidFormat values (that you may extract from the previous SAMLResponse sent by the IdP).

If you don't provide those values, then a saml:NameID of the format entity will be set (as the one you shared).

**Comment by Loki-Afro** [comment]
@pitbulk than I would say the sample application is some kinda broken because the 
```
<saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" SPNameQualifier="superFancySp2">https://idp.ssocircle.com</saml:NameID>
```

always results from when a new `LoginResponse` is constrcted, or am I missing something?

**Comment by pitbulk** [comment]
The "sample app" is just an example, you are free to modify it with your needs.

If you want to provide a PR extending it you are welcome, you may need to store on session the nameid format and retrieve on the do_logout view the nameid and nameid_format from the session and provide them to the logout method.
