### ISSUE TITLE
Some unit tests are testing for wrong conditions

### ISSUE THREAD

**Issue by cgdt** [onelogin/java-saml#134]
Some tests like eg. AuthnResponseTest.testOnlyRetrieveAssertionWithIDThatMatchesSignatureReference() or LogoutRequestTest.testGetNameIdDataWrongKey() are testing wrong conditions. Especially, the ExpectedException object is incorrectly placed. For instance have a look at: 
```
public void testOnlyRetrieveAssertionWithIDThatMatchesSignatureReference() throws Exception {
	expectedEx.expect(ValidationError.class);
	expectedEx.expectMessage("SAML Response could not be processed");

	Saml2Settings settings = new SettingsBuilder().fromFile("config/config.my.properties").build();
	String samlResponseEncoded = Util.getFileAsString("data/responses/invalids/wrapped_response_2.xml.base64");
	SamlResponse samlResponse = new SamlResponse(settings, newHttpRequest(samlResponseEncoded));

	String nameID = samlResponse.getNameId();
	assertFalse(samlResponse.isValid());
	assertFalse("root@example.com".equals(nameID));
}
```
that test expects a ValidationError exception when calling isValid() but the exception is thrown in the SamlResponse() constructor, so the isValid() function will never be called and never be tested.

The correct placement of the expectedEx calls would be immediately before the call that should raise the exception:
```
public void testOnlyRetrieveAssertionWithIDThatMatchesSignatureReference() throws Exception {
	Saml2Settings settings = new SettingsBuilder().fromFile("config/config.my.properties").build();
	String samlResponseEncoded = Util.getFileAsString("data/responses/invalids/wrapped_response_2.xml.base64");
	SamlResponse samlResponse = new SamlResponse(settings, newHttpRequest(samlResponseEncoded));

	String nameID = samlResponse.getNameId();

	expectedEx.expect(ValidationError.class);
	expectedEx.expectMessage("SAML Response could not be processed");
	samlResponse.isValid();

	assertFalse("root@example.com".equals(nameID));
}
```
This test will now fail because the exception is thrown when the samlResponse object should be created.

BTW, since isValid() should throw testing its return value is useless and the following `assertFalse("root@example.com".equals(nameID));` test is also useless.

**Comment by pitbulk** [comment]
Thanks, I will review them.
Do you have a PR to solve the issues you found?

**Comment by cgdt** [comment]
Not yet. Especially, I don't know how to fix the `testOnlyRetrieveAssertionWithIDThatMatchesSignatureReference()` unit test so that `new SamlResponse()` doesn't throw anymore.

**Comment by cgdt** [comment]
@pitbulk pls have a look [at my current changes](https://github.com/cgdt/java-saml/tree/unit-tests-wrong-conditions).

- I fixed two tests in LogoutRequestTest by introducing a new private key sp4.key which I use in those tests instead of the sp3.key (which was the root cause for the exception thrown in the first (wrong) place)
- I moved the ExpectedException object usage to the correct places
- added some // TODO comments where I'm not sure if it is correctly placed now (e.g. the `AuthTest.testLogoutSignedFail()` test wants to check the `logout` function but creating the Auth object fails because the sp certificate is not available. So `auth.logout()` can not be called anyway. Does that test make sense?

And yes, some unit tests are failing now.

**Comment by pitbulk** [comment]
Can you rebase (I already fixed on master the tests you originally reported) and create PR so I will be able to solve test that fails and merge?

**Comment by cgdt** [comment]
see PR #135

**Comment by pitbulk** [comment]
Thanks, I will review in a while
