### ISSUE TITLE
NameId not parsed in IdP initiated single logout 

### ISSUE THREAD

**Issue by sibiantony** [onelogin/java-saml#136]
Using java-saml library with ADFS as the IdP. The SSO works just fine with encryption, signing etc. 
However, for an IdP initiated single logout, I can see that

1.  Auth.java -> `processSLO(Boolean keepLocalSession, String requestId)`
`
  if (!keepLocalSession) {
					request.getSession().invalidate();
				}`

How to ensure that the above is indeed invalidating the session of the requested user ? It could have happened that the original SSO user has logged out and another user logged in manually. Shouldn't the logout be handled by looking up the subject and invalidating the session for that subject by the application (say, from a db entry or so) ?

2. That brings to the next problem. The SAMLRequest from IdP has a NameId field. However, LogoutRequest doesn't seem to parse (`LogoutRequest.java`) the `NameId` from the request. And Auth `getNameId()` is `null`. Looks like LogoutRequest is written for SP initiated SLO ?

**Comment by pitbulk** [comment]
1. In other toolkits like the [php-saml](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L220) I added to the method a callback parameter that can be passed to the processSLO method so the App can define the session handler that properly will manage user invalidation (by default we just close user session by the request.getSession().invalidate();  ).
We should create a new processSLO method supporting this callback parameter (and maybe also an stay parameter to return the SLOURL instead to directly redirect, so you can do something on the App before execute the redirection. Are you interested in provide a PR with that new feature?

2. With the [getNameId](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java#L514) you can provide the LogoutRequest and get the NameId of that LogoutRequest to be used to compare with the NameId (that you maybe had stored on user session before).

The NameId of the Auth is related to the NameId parsed from the SAMLResponse, not related with LogoutRequest.

**Comment by sibiantony** [comment]
Yes, the LogoutRequest.getNameId() should help. Thanks.
I will try to avoid Auth() as much as possible (which also cuts the servlet dependency) and try to use the java-saml-core.
Will send a PR if I plan to use the Auth() class.
