### ISSUE TITLE
Signature value and key of metadata contain CR

### ISSUE THREAD

**Issue by gitterjoe** [onelogin/java-saml#138]
My problem is basically described in the title. When generating the metadata via 

`Auth auth = new Auth(samlSettingsFileName);`
`samlSettings = auth.getSettings();`
`metadata = samlSettings.getSPMetadata();`
`metadataErrors = Saml2Settings.validateMetadata(metadata);`

and returning `metadata`, the `ds:SignatureValue` and `ds:X509Certificate` contain CRs. Shibboleth has problems validating the signature as there are CRs in it where there should not be any.

> <ds:SignatureValue>
> Ot+c2RCcHuCZyjtO0zG5hiC1woQ/Qt1Q7+QLmicPNx3/oAKSZaXsKW0myezSsj3vTo2vL0AleGqN
> 
> Hh5jRok5GA+/oAn2aC9oIq1eWvrOCql4DmJq/QK6Tg12jJ8EcrS53OfxUYU+TxUKgv8K/FluKV4O
> 
> Y0uiXlcQoMYfcq+OTQZiDxluPWQ0Nc7dQcOfwfaFQshs9x5Yc6PjdTXEwf7JnA9rkEB3zDwMG85S
> 
> IAPhV75tjDXen1VE1IQdB1DzGMrIx5t8+Cx+zOxw/RmBDv2CpV/cXkOxbp/lJh5IS7yu8Cs+EC6C
> 
> lZR0JiTN9veWy4RX79ZQh+lJPzn2h8J/UL8adA==
> </ds:SignatureValue>
> <ds:KeyInfo>
> <ds:X509Data>
> <ds:X509Certificate>
> MIICNTCCAZ6gAwIBAgIES343gjANBgkqhkiG9w0BAQUFADBVMQswCQYDVQQGEwJVUzELMAkGA1UE
> 
> CAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDTALBgNVBAoMBFdTTzIxEjAQBgNVBAMMCWxv
> 
> Y2FsaG9zdDAeFw0xMDAyMTkwNzAyMjZaFw0zNTAyMTMwNzAyMjZaMFUxCzAJBgNVBAYTAlVTMQsw
> 
> CQYDVQQIDAJDQTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzENMAsGA1UECgwEV1NPMjESMBAGA1UE
> 
> AwwJbG9jYWxob3N0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUp/oV1vWc8/TkQSiAvTou
> 
> sMzOM4asB2iltr2QKozni5aVFu818MpOLZIr8LMnTzWllJvvaA5RAAdpbECb+48FjbBe0hseUdN5
> 
> HpwvnH/DW8ZccGvk53I6Orq7hLCv1ZHtuOCokghz/ATrhyPq+QktMfXnRS4HrKGJTzxaCcU7OQID
> 
> AQABoxIwEDAOBgNVHQ8BAf8EBAMCBPAwDQYJKoZIhvcNAQEFBQADgYEAW5wPR7cr1LAdq+IrR44i
> 
> QlRG5ITCZXY9hI0PygLP2rHANh+PYfTmxbuOnykNGyhM6FjFLbW2uZHQTY1jMrPprjOrmyK5sjJR
> 
> O4d1DeGHT/YnIjs9JogRKv4XHECwLtIVdAbIdWHEtVZJyMSktcyysFcvuhPQK8Qc/E/Wq8uHSCo=
> 
> </ds:X509Certificate>

Why is that so? Is that a potential bug? Am I missing something? In `<ds:X509Data><ds:X509Certificate>` the same key is printed as it should be.

Used version is `2.1.0`

**Comment by pitbulk** [comment]
Never heard that shibboleth has issues handling with spaces. Can you provide info where you read it?

XML Signature signs part of an XML Document starting with a given element (i.e. a sub tree in DOM) after it is normalized with a C14N algorithm. The standard C14N algorithm you use preserves line breaks and white spaces (see http://www.w3.org/TR/xml-c14n#Example-WhitespaceInContent).

So all line breaks in the signed part of the original document (including between last tag of data and the <Signature> tag, and between </Signature> and the next closing tag) *must be preserved so as not to alter the signature. 

The line breaks and spaces in the Signature element itself are not important and you can remove then when without altering the signature, so you can do that on your metadata generator page.

If you want to provide a PR that add an extra parameter (keepWhiteSpaces, true as default) to the [addSign](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java#L1030) so if keepWhiteSpaces = false, the method removes whitespaces of the DOM before sign it, and later remove whitespaces of the Signature elements, in addition to add that keepWhiteSpaces to the [signMetadata](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/Metadata.java#L378) method

 I'm ok with that and will include, but I don't think right now we are now following the SAML standard.

**Comment by gitterjoe** [comment]
I guess I haven't stated clearly what the problem is. It is not the document itself, but the generated signature that is added afterwards.

Lets say I have the following metadata, generated by calling
`metadata = samlSettings.getSPMetadata();` : [metadataToBeSigned.txt](https://github.com/onelogin/java-saml/files/1579243/metadataToBeSigned.txt)

Signing happens automatically and adds some lines and looks afterwards like this:
[metadataSigned.txt](https://github.com/onelogin/java-saml/files/1579244/metadataSigned.txt)

The content of the files is pretty printed, keys exchanged and some elements removed. But the principle still is the same. 

My intention was, that the added `<ds:SignatureValue>` and `<ds:KeyInfo><ds:X509Data><ds:X509Certificate>` should not contain whitespaces. Those values are added after signing, right? Also it looks strange that there are three keys, all but the key in  `</ds:Signature>` identical. 

If you say that should not be a problem (it seems your text targets the **content** to be signed, not the signature itself) that would would be okay for me. 

The information comes from a customer using Shibboleth as an IdP.

**Comment by pitbulk** [comment]
If you review the sign method you will see that we use XMLSignature class (3rd party) and we use its methods  addDocument, addKeyInfo and sign. After all we call the util.convertDocumentToString method that uses the standard org.apache.xml.security.utils.XMLUtils methods to transform the DOM to String with the canonization c14nMethod... I maintain other toolkits and all have similar inputs.

If you review that link: https://www.testshib.org/metadata/testshib-providers.xml
Here are described metadata from a Test shib IdP, and you will see that it contains spaces and CRs.

Maybe your customer is doing something wrong with the metadata generated by java-saml.

**Comment by gitterjoe** [comment]
That is a valid point. I'll see what they can tell me about it. Funny fact: they could import the signed metadata via our endpoint. It's a little bit strange. 

Thanks for your help, I guess this issue can be considered solved.
