### ISSUE TITLE
onelogin.saml2.sp.nameidformat points to mysterious lib/Saml2/Constants.php

### ISSUE THREAD

**Issue by veselov** [onelogin/java-saml#143]
In the README, for the values accepted for onelogin.saml2.sp.nameidformat, an non-existing file of lib/Saml2/Constants.php is referenced.

**Comment by pitbulk** [comment]
copy&paste from the php-saml toolkit ;) .
Fixed at https://github.com/onelogin/java-saml/commit/94b3ed8e3fd8003534a197c2ee9f608d7df59228
