### ISSUE TITLE
OneLogin Metadata load in ADFS (Windows 2012) fails 

### ISSUE THREAD

**Issue by dazed19** [onelogin/java-saml#144]
I hit a problem trying to setup SAML integration between OneLogin Java SAML and ADFS (Windows 2012).

When adding a Relaying Party Trust I got an Error (attached) indicating missing encoding in XML header

![adfs_utf_encoding error](https://user-images.githubusercontent.com/5738071/35502980-a7aae17a-04d6-11e8-84aa-24cd6446277c.png)

I fixed this by changing com.onelogin.saml2.settings.Metadata.getMetadataTemplate to include UTF-16 encoding...

```
	private static StringBuilder getMetadataTemplate() {

		StringBuilder template = new StringBuilder();
		template.append("<?xml version=\"1.0\" encoding=\"UTF-16\"?>");
                ...
```

**Comment by pitbulk** [comment]
Noted, notice that in the [metadata endpoint example](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/webapp/metadata.jsp#L10), charset header is set to UTF-8

**Comment by dazed19** [comment]
Just to flag that it's possible that I introduced the problem here by copying and saving the Metadata output from browser (on Windows) before using ADFS Relaying Party Trust wizard.  

Our ADFS server isn't internet connected (as it's serving internal user population) so I was not able to get it to pull Metadata directly from our OneLogin SP endpoint via HTTP.  Hence saving it via browser - which *may* have altered the encoding.

In the end I have gone with 
`template.append("<?xml version=\"1.0\" encoding=\""+Charset.defaultCharset()+""?>");
 `
...with a slightly different way of saving/copying the file
