### ISSUE TITLE
Handle Exceptions inside SamlResponse Class

### ISSUE THREAD

**Issue by necouchman** [onelogin/java-saml#146]
After doing some implementation work with the `SamlResponse` class, it looks like several exceptions are not handled internally within the class.  In particular, using version 2.2.0, I had to handle the following exceptions:

- IOException
- ParserConfigurationException
- SAXException
- SettingsException
- ValidationError
- XPathExpressionException

A couple of those (Settings, Validation) are ones that should be handled by the user; however, the rest of them seem like stuff internal to `SamlResponse` that could be abstracted into a single class (`SamlResponseException` or something like that), so that those using the class wouldn't have to worry about handling quite so many exceptions.

**Comment by pitbulk** [comment]
@necouchman It seems a good idea to abstract all those exceptions under a SamlResponseException, but it should contain the original Exception so a dev can handle what is going on.

Open for PRs ;)

**Comment by necouchman** [comment]
@pitbulk Totally agreed - we've done similar in the Guacamole project, implementing a top-level `GuacamoleException` class, but at least allowing the original exception to be passed through so that the details are available.  I'll start looking at implementing that top-level exception class and submit a PR if/when I get something written.

**Comment by pitbulk** [comment]
Fantastic

**Comment by pitbulk** [comment]
Any progress?

**Comment by necouchman** [comment]
Sorry for the delay - I'm working on this...hopefully have something in the next few days...
