### ISSUE TITLE
Confusing validation error

### ISSUE THREAD

**Issue by veselov** [onelogin/java-saml#149]
I spent quite a while figuring this out, and I think this can be improved.
I was getting SAML responses that were signed with a certificate different from the certificate that is configured in the IdP.
The error was "signature validation failed". The call was actually passed down to XmlSec. XmlSec tried to validate the signature in the response with the configured certificate, rightfully blowing chunks.
It'd be a lot better if the error was that the certificates didn't match.

**Comment by pitbulk** [comment]
That is something that we do in other toolkits, for example in the [python-saml toolkit](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L1133). We first verify that the certiicate used in the XML matches one available on the settings, then we validate the Signature.

Are you able to provide a PR to improve the current validation signature process as you suggested?

**Comment by veselov** [comment]
Sure, I'll a PR together, thank you.
