### ISSUE TITLE
Signature Algorithm Error with Microsoft ADFS Version 4

### ISSUE THREAD

**Issue by alexandermontgomery** [onelogin/java-saml#152]
Hello - I am getting this issue from a partner IDp I am trying to integrate with. Any help would be appreciated.

`SAML request is not signed with expected signature algorithm. SAML request is signed with signature algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 . Expected signature algorithm is http://www.w3.org/2000/09/xmldsig#rsa-sha1`

Here are my settings:

```java
// Force toolkit to reject unsigned or unencrypted messages if it expects them signed or encrypted
        // Also will reject the messages if not strictly follow the SAML spec
        samlSettings.put("onelogin.saml2.strict", true);

        // Enable debug mode (to print errors)
        samlSettings.put("onelogin.saml2.debug", DEBUG);


        // SP Settings
        samlSettings.put("onelogin.saml2.sp.entityid", config.getSpEntityId());
        samlSettings.put("onelogin.saml2.sp.assertion_consumer_service.url",
                // dynamic
        );
        // onelogin toolkit only supports POST Binding for login
        samlSettings.put("onelogin.saml2.sp.assertion_consumer_service.binding", "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST");
        samlSettings.put("onelogin.saml2.sp.single_logout_service.url",
                // dynamic
        );
        // onelogin toolkit only supports Redirect Binding for single logout
        samlSettings.put("onelogin.saml2.sp.single_logout_service.binding", "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect");
        samlSettings.put("onelogin.saml2.security.want_xml_validation",true);
        samlSettings.put("onelogin.saml2.sp.x509cert", spCertificate);
        samlSettings.put("onelogin.saml2.sp.privatekey", spCertificateKey);
        // Sign all outgoing messages
        samlSettings.put("onelogin.saml2.security.authnrequest_signed", true);
        samlSettings.put("onelogin.saml2.security.logoutrequest_signed", true);
        samlSettings.put("onelogin.saml2.security.logoutresponse_signed", true);
        // Use stronger signing algorithm (default is sha1)
        samlSettings.put("onelogin.saml2.security.signature_algorithm ", "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
        // No authncontext needed
        samlSettings.put("onelogin.saml2.security.requested_authncontext", "");

        // IDP Settings
        samlSettings.put("onelogin.saml2.idp.entityid", idpMetadata.getEntityID());
        samlSettings.put("onelogin.saml2.idp.single_sign_on_service.url",
                // Throws SettingsException if not found, but since it's required we want it propagated up
                // dynamic
        );
        try {
            samlSettings.put("onelogin.saml2.idp.single_logout_service.url",
                    // dynamic
            );
        } catch (SettingsException e) {
            // No SLO role descriptor found
            // Do nothing - don't set the single_logout_service setting in the OneLogin framework settings
        }
        // The onelogin SAML toolkit only requests one certificate even though the metadata may have a signing and an
        // encryption certificate - but almost all the time the signing and encryption certificates are the same
        try {
            samlSettings.put("onelogin.saml2.idp.x509cert",
                    SAMLUtils.getCertificatesFromIdpSsoRoleDescriptor(idpRoleDescriptor).get(UsageType.SIGNING)
            );
        } catch (CertificateException e) {
            log.error("There was a problem reading the certificate from the metadata", e);
            throw new SettingsException("There was a problem reading the certificate from the metadata", SettingsException.CERT_NOT_FOUND);
        }
        samlSettings.put("onelogin.saml2.security.want_assertions_encrypted", config.getEncryptedAssertion());
        samlSettings.put("onelogin.saml2.security.want_nameid_encrypted", config.getEncryptedNameId());
```

**Comment by pitbulk** [comment]
You may modify this line
```
samlSettings.put("onelogin.saml2.security.signature_algorithm ", "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
```
by
```
samlSettings.put("onelogin.saml2.security.signature_algorithm ", "http://www.w3.org/2000/09/xmldsig#rsa-sha1");
```

Or change settings at the IdP side to use the rsa-sha256 algorithm

**Comment by Surender-godara** [comment]
here is complete response 

<samlp:Response ID="_592c022f-e85e-4d23-b55b-9141c95cd2a5" Version="2.0" IssueInstant="2014-01-31T15:36:31.357Z" Destination="https://login.microsoftonline.com/login.srf" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_049917a6-1183-42fd-a190-1d2cbaf9b144" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
  <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://WS2012R2-0.contoso.com/adfs/services/trust</Issuer>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
  </samlp:Status>
  <Assertion ID="_7e3c1bcd-f180-4f78-83e1-7680920793aa" IssueInstant="2014-01-31T15:36:31.279Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
    <Issuer>http://WS2012R2-0.contoso.com/adfs/services/trust</Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
        <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
        <ds:Reference URI="#_7e3c1bcd-f180-4f78-83e1-7680920793aa">
          <ds:Transforms>
            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
          </ds:Transforms>
          <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
          <ds:DigestValue>CBn/5YqbheaJP425c0pHva9PhNY=</ds:DigestValue>
        </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>TciWMyHW2ZODrh/2xrvp5ggmcHBFEd9vrp6DYXp+hZWJzmXMmzwmwS8KNRJKy8H7XqBsdELA1Msqi8I3TmWdnoIRfM/ZAyUppo8suMu6Zw+boE32hoQRnX9EWN/f0vH6zA/YKTzrjca6JQ8gAV1ErwvRWDpyMcwdYCiWALv9ScbkAcebOE1s1JctZ5RBXggdZWrYi72X+I4i6WgyZcIGai/rZ4v2otoWAEHS0y1yh1qT7NDPpl/McDaTGkNU6C+8VfjD78DrUXEcAfKvPgKlKrOMZnD1lCGsViimGY+LSuIdY45MLmyaa5UT4KWph6dA==</ds:SignatureValue>
      <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>MIIC7jCCAdagAwIBAgIQRrjsbFPaXIlOG3GTv50fkjANBgkqhkiG9w0BAQsFADAzMTEwLwYDVQQDEyhBREZTIFNpZ25pbmcgLSBXUzIwMTJSMi0wLnN3aW5mb3JtZXIuY29tMB4XDTE0MDEyMDE1MTY0MFoXDTE1MDEyMDE1MTY0MFowMzExMC8GA1UEAxMoQURGUyBTaWduaW5nIC0gV1MyMDEyUjItMC5zd2luZm9ybWVyLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKe+rLVmXy1QwCwZwqgbbp1/+3ZWxd9T/jV0hpLIIWr+LCOHqq8n8beJvlivgLmDJo8f+EITnAxWcsJUvVai/35AhHCUq9tc9sqMp5PWtabAEMb2AU72/QlX/72D2/NbGQq1BWYbqUpgpCZ2nSgvlWDHlCiUo//UGsvfox01kjTFlmqQInsJVfRxF5AcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAi8c6C4zaTEc7aQiUgvnGQgCbMZbhUXXLGRpjvFLKaQzkwa9eq7WLJibcSNyGXBa/SfT5wJgsm3TPKgSehGAOTirhcqHheZyvBObAScY7GOT+u9pVYp6raFrc7ez3c+CGHeV/tNvy1hJNs12FYH4X+ZCNFIT9tprieR25NCdi5SWUbPZL0tVzJsHc1y92b2M2FxqRDohxQgJvyJOpcg2mSBzZZIkvDg7gfPSUXHVS1MQs0RHSbwq/XdQocUUhl9/e/YWCbNNxlM84BxFsBUok1dH/gzBySx+Fc8zYi7cOq9yaBT3RLT6cGmFGVYZJW4FyhPZOCLVNsLlnPQcX3dDg9A==</ds:X509Certificate>
        </ds:X509Data>
      </KeyInfo>
    </ds:Signature>
    <Subject>
      <NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">ABCDEG1234567890</NameID>
      <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <SubjectConfirmationData InResponseTo="_049917a6-1183-42fd-a190-1d2cbaf9b144" NotOnOrAfter="2014-01-31T15:41:31.357Z" Recipient="https://login.microsoftonline.com/login.srf" />
      </SubjectConfirmation>
    </Subject>
    <Conditions NotBefore="2014-01-31T15:36:31.263Z" NotOnOrAfter="2014-01-31T16:36:31.263Z">
      <AudienceRestriction>
        <Audience>urn:federation:MicrosoftOnline</Audience>
      </AudienceRestriction>
    </Conditions>
    <AttributeStatement>
      <Attribute Name="IDPEmail">
        <AttributeValue>administrator@contoso.com</AttributeValue>
      </Attribute>
    </AttributeStatement>
    <AuthnStatement AuthnInstant="2014-01-31T15:36:30.200Z" SessionIndex="_7e3c1bcd-f180-4f78-83e1-7680920793aa">
      <AuthnContext>
        <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
      </AuthnContext>
    </AuthnStatement>
  </Assertion>
</samlp:Response>
