### ISSUE TITLE
IDP response status is Responder not Success and not getting ADFS claim in response

### ISSUE THREAD

**Issue by Surender-godara** [onelogin/java-saml#157]
I have setup onelogin saml with  ADFS as IDP, in ADFS i have setup claim for mail but i am not getting this in response. Here is the ADFS response

 <samlp:Status>
        <samlp:StatusCode 
            Value="urn:oasis:names:tc:SAML:2.0:status:Responder" />
    </samlp:Status>

what can be the issue

**Comment by pitbulk** [comment]
The cause should be registered on ADFS trace log.

Possible reasons:
- ADFS does not support the NameID Format defined on the AuthNRequest
- ADFS does not support the AuthN Context
- ADFS requires AuthNRequest signed
- ADFS requires AuthNRequest signed with a specific algorithm

**Comment by Surender-godara** [comment]
Thanks for Quick response. I'll check ADFS logs and then get back to you

**Comment by Surender-godara** [comment]
Hi,
ADFS is using two different certificate for Signing and Encrypting SP request. How can i add two SP certi for sign and encryption in One Login setting builder.

**Comment by pitbulk** [comment]
java-saml toolkit only supports the same private key/certificate for the SP.

IdP multi certificate is supported

**Comment by Surender-godara** [comment]
thanks

**Comment by poidog68** [comment]
Surender,
I think I am getting the  same issue. Were you able to resolve your issue and can you share your solution?

**Comment by pitbulk** [comment]
@poidog68 you may ask ADFS admin to review their error log to figure out the real reason for rejecting the AuthNRequest and sending a SAMLResponse with no Success status.

**Comment by Surender-godara** [comment]
@poidog68 yes, I fixed the issue.  I was getting the this error because of certificate mismatch between ADFS and SAML client.

**Comment by bhushan1987** [comment]
Is there any way that we can get the error message in SAML response? so that if anything goes wrong, we need not check the logs of AD FS.
