### ISSUE TITLE
Need help in java based integration

### ISSUE THREAD

**Issue by jakkamprashanth** [onelogin/java-saml#159]
@pitbulk 
Hi,
I am trying to use one login saml java tool kit, my requirement is:
i do not want to open IDP login page , instead ,credentials passed as part of my application login request should be considered. In other words, i just need to communicate to IDP and know if user is valid or not and also retrieve attributes of user.
How do i avoid opening IDP login page after sending auth request?

**Comment by pitbulk** [comment]
```
I do not want to open IDP login page , instead ,credentials passed as part of my application login request should be considered.
```
This is not how SAML works, so you can't do that with java-saml.
