### ISSUE TITLE
Regarding IDP initiated login flow

### ISSUE THREAD

**Issue by AjayPara** [onelogin/java-saml#161]
Hi,
  I am using java-saml library for  SSO integration and it works fine for SP-initiated login flow but I have a confusion regarding IDP initiated login flow.

  Can you explain how the certificate validation will happen in case of IDP initiated login flow?
  For me, The IDP entity id and certificate comes dynamically based on the logging in user.

**Comment by pitbulk** [comment]
> Can you explain how the certificate validation will happen in case of IDP initiated login flow?

The same way of a SP-initiated SSO.

In the SP-initiated SSO we have the following steps:
1. SP sends AuthNRequest
2. IdP authenticates user
3. IdP send a SAMLResponse

On the IdP-initiated SSO,if we assume that the user already has a session on the IdP, only the step 3 is executed.

The SAMLResponse has the entity Id and the certificate inside. But before validate it, IdP and SP need to trust each other (exchanging the metadata).

**Comment by AjayPara** [comment]
Can you please explain more about this?

"The SAMLResponse has the entity Id and the certificate inside. But before validate it, IdP and SP need to trust each other (exchanging the metadata)."

Do we need to take metadata XML also from IDP? 

Currently, we are taking IDP login URL and certificate.

**Comment by pitbulk** [comment]
In order to interact, SP and IdP must previously to exchange its metadata + certs.

So you need to configure on the SP settings, all data related to the IdP (as you previously, otherwise the SP-initiated SSO process fails, and you said you were able to succeed on it).

Read this [SAML explanation](https://github.com/jch/saml)

**Comment by AjayPara** [comment]
Thanks for the given link..nicely explained.

I have already given SP entity ID and ACS URL at IDP while creating the application, That's why SP-initiated SSO is successful.

but on IdP-initiated SSO, I am receiving the SAMLResponse at ACS URL from there I am calling processResponse() method of Auth() class but it is failing because I don't have all the SAML settings(entity id and certificate etc) are not available(for me these settings comes dynamically based on the user).

**Comment by pitbulk** [comment]
Can't be configured dynamically based on the SAMLResponse, otherwise, any SAMLResponse sent to your ACS should be dynamically registered and accepted.

**Comment by AjayPara** [comment]
Ok.

So, to verify the SAMLResponse's signature in IdP-initiated SSO, I need to get the certificate from SAMLResponse and process.

is it correct?

**Comment by pitbulk** [comment]
You first check that the certificate on the SAMLResponse matches the one you have stored on SP settings for the IdP, and then you validate the Signature.

**Comment by AjayPara** [comment]
I can't get the certificate from SP until unless I get the principle(nameid) from SAMLResponse.

Can I get the nameid from SAMLResponse before signature validation?

**Comment by pitbulk** [comment]
NameID is related to the user... why with the NameID you are trying to get the related SP metadata?
If you have different sets of users, implement more than 1 SP...

**Comment by AjayPara** [comment]
I think I misunderstood your point

"You first check that the certificate on the SAMLResponse matches the one you have stored on SP settings for the IdP, and then you validate the Signature."

Did you mean you want me to check the **onelogin.saml2.sp.x509cert** property value with the certificate on the SAMLResponse?

**Comment by pitbulk** [comment]
you validate SAMLResponse signature with **onelogin.saml2.idp.x509cert**

**Comment by AjayPara** [comment]
Yes.We do that even in SP-initiated SSO also.

But in my scenario is I have multiple users with one IDP for each user and we have stored these details by mapping the user and IDP details.

When the user tries to login SP-initiated SSO by entering the user then we will pick the IDP login URL and certificate and we do log in and it works fine.

In case of IDP-initiated SSO, I can't get the IDP details(certificate to validate SAMLResponse) until unless I have a user (nameid).

**Comment by pitbulk** [comment]
ok, then I think you are able to retrieve the nameid, and then do the validation..

**Comment by AjayPara** [comment]
Ok,Thanks.

**Comment by AjayPara** [comment]
One last question.
Is it the correct to retrieve the nameid before SAMLResponse validation ?

**Comment by pitbulk** [comment]
You can trust the content of a SAMLResponse after validating it.

If you retrieve before validating the SAMLResponse the NameID and do something with its value (for example, create an account or log the related used on an app, you are doing it wrong and turning your app open to be hacked.
