### ISSUE TITLE
Allow loading properties in XML format

### ISSUE THREAD

**Issue by s1m3n** [onelogin/java-saml#162]
It would be great if you could pass either a .properties or a .xml file with the properties to the com.onelogin.saml2.Auth constructor. 

The code change should be as simple as using the Properties.loadFromXML(stream)  method.

**Comment by pitbulk** [comment]
The Auth class support a [filename](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L197) or a [Saml2Settings](Saml2Settings) object.

The Saml2Settings object can be generated by the [SettingsBuilder](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java#L32) class using:
- [fromFile](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java#L118) Providing the filename of the file that contains the properties
- [fromProperties](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java#L149) Providing a   java.util.Properties object
- [fromValues](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java#L162) Providing a   Map<String, Object> object

So you already have different ways to import the data settings, if you want to add a new fromXML method to the SettingsBuilder class we are open to review and merge the PR.
