### ISSUE TITLE
fail to decrypt assertion

### ISSUE THREAD

**Issue by EricBlanquer** [onelogin/java-saml#163]
Hi,
into the SamlResponse.java method "decryptAssertion",
there is a comment "// We need to Remove the saml:EncryptedAssertion Node"
but the code try to remove a not present node into the SAMLResponse: "/samlp:Response/saml:EncryptedAssertion/saml:Assertion"
so, the "Node assertionNode = AssertionDataNodes.item(0);" is null
and the "assertionNode.getParentNode()" throws a NullPointerException

**Comment by pitbulk** [comment]
That means that the process to decrypt the Assertion
```
Util.decryptElement(encryptedData, key);
```
failed, or the encypted data does not contain a saml:EncryptedAssertion/saml:Assertion element

I can catch it, and instead throw a Exception, verify that a saml:EncryptedAssertion/saml:Assertion element exists by:
```
NodeList encryptedDataNodes = Util.query(dom, "/samlp:Response/saml:EncryptedAssertion/xenc:EncryptedData");
if (encryptedDataNodes.getLength() == 0) {
throw new ValidationError("No /samlp:Response/saml:EncryptedAssertion/xenc:EncryptedData element found");
}
Element encryptedData = (Element) encryptedDataNodes.item(0);
Util.decryptElement(encryptedData, key);

NodeList AssertionDataNodes = Util.query(dom, "/samlp:Response/saml:EncryptedAssertion/saml:Assertion");
if (encryptedDataNodes.getLength() == 0) {
throw new ValidationError("No /samlp:Response/saml:EncryptedAssertion/saml:Assertion element found");
}
Node assertionNode = AssertionDataNodes.item(0);
assertionNode.getParentNode().getParentNode().replaceChild(assertionNode, assertionNode.getParentNode());
```

**Comment by EricBlanquer** [comment]
thanks,
no the SAMLResponse of the ADFS server doesn't contains this element

<samlp:Response
  ID="_27eb1206-e96d-4b8e-b627-24b3b7fbde35"
  Version="2.0"
  IssueInstant="2018-04-26T12:57:32.083Z"
  Destination=" ... "
  Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
  InResponseTo="ONELOGIN_ebc2c584-5c2f-4123-ac78-60ca36f7f7f3"
  xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion"> ... </Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <EncryptedAssertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
        <xenc:EncryptedData Type="http://www.w3.org/2001/04/xmlenc#Element" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" />
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#">
                    <e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
                        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                    </e:EncryptionMethod>
                    <KeyInfo>
                        <ds:X509Data xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                            <ds:X509IssuerSerial>
                                <ds:X509IssuerName> ... </ds:X509IssuerName>
                                <ds:X509SerialNumber> ... </ds:X509SerialNumber>
                            </ds:X509IssuerSerial>
                        </ds:X509Data>
                    </KeyInfo>
                    <e:CipherData>
                        <e:CipherValue> ... </e:CipherValue>
                    </e:CipherData>
                </e:EncryptedKey>
            </KeyInfo>
            <xenc:CipherData>
                <xenc:CipherValue> ... </xenc:CipherValue>
            </xenc:CipherData>
        </xenc:EncryptedData>
    </EncryptedAssertion>
</samlp:Response>

**Comment by EricBlanquer** [comment]
it is a bad response of the ADFS server?

**Comment by pitbulk** [comment]
I'm not able to see inside EncryptedAssertion/EncryptedData so can't debug.

Can you replace the code you have by the one I provided?
Also try adding a debug on that method and let me know the value of the dom
[you can print it with  Util.convertDocumentToString(dom)] so we can see what is going on.

**Comment by pitbulk** [comment]
A possible issue is that the Assertion element included on the EncryptedData element has no namespace.
I created a workaround at php-saml, but did not apply it on java-saml. Please confirm if you are experiencing that issue.

**Comment by EricBlanquer** [comment]
I've uploaded a "SAML_response.txt" file, that's the result of the "Util.convertDocumentToString(dom)" without sensible datas

I've replaced the existing code by your new code and changed the "encryptedDataNodes.getLength()" by "AssertionDataNodes.getLength()",

now the "auth.processResponse();" throws this new exception...

**Comment by EricBlanquer** [comment]
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
 Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
  Destination=" ...snipped... " 
  ID="_27eb1206-e96d-4b8e-b627-24b3b7fbde35" InResponseTo="ONELOGIN_ebc2c584-5c2f-4123-ac78-60ca36f7f7f3"
   IssueInstant="2018-04-26T12:57:32.083Z" Version="2.0">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion"> ...snipped... </Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success">
        </samlp:StatusCode>
    </samlp:Status>
    <EncryptedAssertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
        <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Type="http://www.w3.org/2001/04/xmlenc#Element">
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc">
            </xenc:EncryptionMethod>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#">
                    <e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
                        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1">
                        </DigestMethod>
                    </e:EncryptionMethod>
                    <KeyInfo>
                        <ds:X509Data xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                            <ds:X509IssuerSerial>
                                <ds:X509IssuerName> ...snipped... </ds:X509IssuerName>
                                <ds:X509SerialNumber> ...snipped... </ds:X509SerialNumber>
                            </ds:X509IssuerSerial>
                        </ds:X509Data>
                    </KeyInfo>
                    <e:CipherData>
                        <e:CipherValue> ...snipped... </e:CipherValue>
                    </e:CipherData>
                </e:EncryptedKey>
            </KeyInfo>
            <xenc:CipherData>
                <xenc:CipherValue> ...snipped... </xenc:CipherValue>
            </xenc:CipherData>
        </xenc:EncryptedData>
    </EncryptedAssertion>
</samlp:Response>

**Comment by EricBlanquer** [comment]
`<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
 Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
  Destination=" ...snipped... " 
  ID="_27eb1206-e96d-4b8e-b627-24b3b7fbde35" InResponseTo="ONELOGIN_ebc2c584-5c2f-4123-ac78-60ca36f7f7f3"
   IssueInstant="2018-04-26T12:57:32.083Z" Version="2.0">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion"> ...snipped... </Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success">
        </samlp:StatusCode>
    </samlp:Status>
    <EncryptedAssertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
        <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Type="http://www.w3.org/2001/04/xmlenc#Element">
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc">
            </xenc:EncryptionMethod>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#">
                    <e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
                        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1">
                        </DigestMethod>
                    </e:EncryptionMethod>
                    <KeyInfo>
                        <ds:X509Data xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                            <ds:X509IssuerSerial>
                                <ds:X509IssuerName> ...snipped... </ds:X509IssuerName>
                                <ds:X509SerialNumber> ...snipped... </ds:X509SerialNumber>
                            </ds:X509IssuerSerial>
                        </ds:X509Data>
                    </KeyInfo>
                    <e:CipherData>
                        <e:CipherValue> ...snipped... </e:CipherValue>
                    </e:CipherData>
                </e:EncryptedKey>
            </KeyInfo>
            <xenc:CipherData>
                <xenc:CipherValue> ...snipped... </xenc:CipherValue>
            </xenc:CipherData>
        </xenc:EncryptedData>
    </EncryptedAssertion>
</samlp:Response>
`

**Comment by pitbulk** [comment]
It seems the decrypt process failed since I still see the EncryptedData element.

**Comment by pitbulk** [comment]
@EricBlanquer , were you able to identify why the decryption process failed?

**Comment by EricBlanquer** [comment]
Hi @pitbulk, and no,
as nobody know how to solve this situation, we have requested to our customer to use what have been approved: a non cipher response
thank you for your involvement :)

**Comment by satyagh2803** [comment]
Hi @EricBlanquer , I am getting exactly the same issue as you got - "Node assertionNode = AssertionDataNodes.item(0);" is null
and the "assertionNode.getParentNode()" throws a NullPointerException". Were you able to resolve this one? Can you please help me out?

Thanks & Regards,
Satya.
