### ISSUE TITLE
ADFS assertion response not as expected by one login

### ISSUE THREAD

**Issue by Surender-godara** [onelogin/java-saml#174]
i have setup one login with ADFS as IDP,but  adfs response is not as expected by one login api ,so it is failing to extract information from adfs response. here is ADFS  assertion response 
```
        <Subject>
            <NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
                    NameQualifier="http://xxx/adfs/services/trust"
                    SPNameQualifier="test_sp"
                    >xxx=</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="s25D38F224660BF3DCD4D53CA601DD3A515334528A"
                                         NotOnOrAfter="2012-10-25T18:23:30.305Z"
                                         Recipient="https://xxx/TestApp/default.aspx"
                                         />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2012-10-25T18:18:30.303Z"
                    NotOnOrAfter="2012-10-25T19:18:30.303Z"
                    >
            <AudienceRestriction>
                <Audience>test_sp</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name">
                <AttributeValue>Joe Bloggs</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
                <AttributeValue>joeb@example.com</AttributeValue>
            </Attribute>
        </AttributeStatement>
```

e.g- ADFS response  tag is <Subject> but one login expected tag is <saml:Subject>.

Please let me know how to resolve this problem

**Comment by Surender-godara** [comment]
full SAMLResponse 
<samlp:Response ID="_592c022f-e85e-4d23-b55b-9141c95cd2a5" Version="2.0" IssueInstant="2014-01-31T15:36:31.357Z" Destination="https://login.microsoftonline.com/login.srf" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_049917a6-1183-42fd-a190-1d2cbaf9b144" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
  <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://WS2012R2-0.contoso.com/adfs/services/trust</Issuer>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
  </samlp:Status>
  <Assertion ID="_7e3c1bcd-f180-4f78-83e1-7680920793aa" IssueInstant="2014-01-31T15:36:31.279Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
    <Issuer>http://WS2012R2-0.contoso.com/adfs/services/trust</Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
        <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
        <ds:Reference URI="#_7e3c1bcd-f180-4f78-83e1-7680920793aa">
          <ds:Transforms>
            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
          </ds:Transforms>
          <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
          <ds:DigestValue>CBn/5YqbheaJP425c0pHva9PhNY=</ds:DigestValue>
        </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>TciWMyHW2ZODrh/2xrvp5ggmcHBFEd9vrp6DYXp+hZWJzmXMmzwmwS8KNRJKy8H7XqBsdELA1Msqi8I3TmWdnoIRfM/ZAyUppo8suMu6Zw+boE32hoQRnX9EWN/f0vH6zA/YKTzrjca6JQ8gAV1ErwvRWDpyMcwdYCiWALv9ScbkAcebOE1s1JctZ5RBXggdZWrYi72X+I4i6WgyZcIGai/rZ4v2otoWAEHS0y1yh1qT7NDPpl/McDaTGkNU6C+8VfjD78DrUXEcAfKvPgKlKrOMZnD1lCGsViimGY+LSuIdY45MLmyaa5UT4KWph6dA==</ds:SignatureValue>
      <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>MIIC7jCCAdagAwIBAgIQRrjsbFPaXIlOG3GTv50fkjANBgkqhkiG9w0BAQsFADAzMTEwLwYDVQQDEyhBREZTIFNpZ25pbmcgLSBXUzIwMTJSMi0wLnN3aW5mb3JtZXIuY29tMB4XDTE0MDEyMDE1MTY0MFoXDTE1MDEyMDE1MTY0MFowMzExMC8GA1UEAxMoQURGUyBTaWduaW5nIC0gV1MyMDEyUjItMC5zd2luZm9ybWVyLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKe+rLVmXy1QwCwZwqgbbp1/+3ZWxd9T/jV0hpLIIWr+LCOHqq8n8beJvlivgLmDJo8f+EITnAxWcsJUvVai/35AhHCUq9tc9sqMp5PWtabAEMb2AU72/QlX/72D2/NbGQq1BWYbqUpgpCZ2nSgvlWDHlCiUo//UGsvfox01kjTFlmqQInsJVfRxF5AcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAi8c6C4zaTEc7aQiUgvnGQgCbMZbhUXXLGRpjvFLKaQzkwa9eq7WLJibcSNyGXBa/SfT5wJgsm3TPKgSehGAOTirhcqHheZyvBObAScY7GOT+u9pVYp6raFrc7ez3c+CGHeV/tNvy1hJNs12FYH4X+ZCNFIT9tprieR25NCdi5SWUbPZL0tVzJsHc1y92b2M2FxqRDohxQgJvyJOpcg2mSBzZZIkvDg7gfPSUXHVS1MQs0RHSbwq/XdQocUUhl9/e/YWCbNNxlM84BxFsBUok1dH/gzBySx+Fc8zYi7cOq9yaBT3RLT6cGmFGVYZJW4FyhPZOCLVNsLlnPQcX3dDg9A==</ds:X509Certificate>
        </ds:X509Data>
      </KeyInfo>
    </ds:Signature>
    <Subject>
      <NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">ABCDEG1234567890</NameID>
      <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <SubjectConfirmationData InResponseTo="_049917a6-1183-42fd-a190-1d2cbaf9b144" NotOnOrAfter="2014-01-31T15:41:31.357Z" Recipient="https://login.microsoftonline.com/login.srf" />
      </SubjectConfirmation>
    </Subject>
    <Conditions NotBefore="2014-01-31T15:36:31.263Z" NotOnOrAfter="2014-01-31T16:36:31.263Z">
      <AudienceRestriction>
        <Audience>urn:federation:MicrosoftOnline</Audience>
      </AudienceRestriction>
    </Conditions>
    <AttributeStatement>
      <Attribute Name="IDPEmail">
        <AttributeValue>administrator@contoso.com</AttributeValue>
      </Attribute>
    </AttributeStatement>
    <AuthnStatement AuthnInstant="2014-01-31T15:36:30.200Z" SessionIndex="_7e3c1bcd-f180-4f78-83e1-7680920793aa">
      <AuthnContext>
        <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
      </AuthnContext>
    </AuthnStatement>
  </Assertion>
</samlp:Response>


here is attachment 
[fullResponse.zip](https://github.com/onelogin/java-saml/files/2098036/fullResponse.zip)

**Comment by Surender-godara** [comment]
Please use Attached zip file as comment full response in not properly displayed.

**Comment by Surender-godara** [comment]
i am not able to extract info form assertion tag like NameID id tag. 

getting this error
HTTP Status 500 - Request processing failed; nested exception is com.onelogin.saml2.exception.ValidationError: No name id found in Document.

**Comment by Surender-godara** [comment]
stack trace of error are here
root cause
com.onelogin.saml2.exception.ValidationError: No name id found in Document.
	com.onelogin.saml2.authn.SamlResponse.getNameIdData(SamlResponse.java:466)
	com.onelogin.saml2.authn.SamlResponse.getNameId(SamlResponse.java:480)
	com.onelogin.saml2.Auth.processResponse(Auth.java:527)
	com.onelogin.saml2.Auth.processResponse(Auth.java:557)

**Comment by pitbulk** [comment]
I executed the following with java-saml 2.3.0
```
		Saml2Settings settings = new SettingsBuilder().fromFile("config/config.my.properties").build();
		String samlResponseEncoded = "PHNhbWxwOlJlc3BvbnNlIElEPSJfNTkyYzAyMmYtZTg1ZS00ZDIzLWI1NWItOTE0MWM5NWNkMmE1IiBWZXJzaW9uPSIyLjAiIElzc3VlSW5zdGFudD0iMjAxNC0wMS0zMVQxNTozNjozMS4zNTdaIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL2xvZ2luLnNyZiIgQ29uc2VudD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNvbnNlbnQ6dW5zcGVjaWZpZWQiIEluUmVzcG9uc2VUbz0iXzA0OTkxN2E2LTExODMtNDJmZC1hMTkwLTFkMmNiYWY5YjE0NCIgeG1sbnM6c2FtbHA9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCI+DQogIDxJc3N1ZXIgeG1sbnM9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPmh0dHA6Ly9XUzIwMTJSMi0wLmNvbnRvc28uY29tL2FkZnMvc2VydmljZXMvdHJ1c3Q8L0lzc3Vlcj4NCiAgPHNhbWxwOlN0YXR1cz4NCiAgICA8c2FtbHA6U3RhdHVzQ29kZSBWYWx1ZT0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnN0YXR1czpTdWNjZXNzIiAvPg0KICA8L3NhbWxwOlN0YXR1cz4NCiAgPEFzc2VydGlvbiBJRD0iXzdlM2MxYmNkLWYxODAtNGY3OC04M2UxLTc2ODA5MjA3OTNhYSIgSXNzdWVJbnN0YW50PSIyMDE0LTAxLTMxVDE1OjM2OjMxLjI3OVoiIFZlcnNpb249IjIuMCIgeG1sbnM9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPg0KICAgIDxJc3N1ZXI+aHR0cDovL1dTMjAxMlIyLTAuY29udG9zby5jb20vYWRmcy9zZXJ2aWNlcy90cnVzdDwvSXNzdWVyPg0KICAgIDxkczpTaWduYXR1cmUgeG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPg0KICAgICAgPGRzOlNpZ25lZEluZm8+DQogICAgICAgIDxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiAvPg0KICAgICAgICA8ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3JzYS1zaGExIiAvPg0KICAgICAgICA8ZHM6UmVmZXJlbmNlIFVSST0iI183ZTNjMWJjZC1mMTgwLTRmNzgtODNlMS03NjgwOTIwNzkzYWEiPg0KICAgICAgICAgIDxkczpUcmFuc2Zvcm1zPg0KICAgICAgICAgICAgPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIiAvPg0KICAgICAgICAgICAgPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgLz4NCiAgICAgICAgICA8L2RzOlRyYW5zZm9ybXM+DQogICAgICAgICAgPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIiAvPg0KICAgICAgICAgIDxkczpEaWdlc3RWYWx1ZT5DQm4vNVlxYmhlYUpQNDI1YzBwSHZhOVBoTlk9PC9kczpEaWdlc3RWYWx1ZT4NCiAgICAgICAgPC9kczpSZWZlcmVuY2U+DQogICAgICA8L2RzOlNpZ25lZEluZm8+DQogICAgICA8ZHM6U2lnbmF0dXJlVmFsdWU+VGNpV015SFcyWk9EcmgvMnhydnA1Z2dtY0hCRkVkOXZycDZEWVhwK2haV0p6bVhNbXp3bXdTOEtOUkpLeThIN1hxQnNkRUxBMU1zcWk4STNUbVdkbm9JUmZNL1pBeVVwcG84c3VNdTZadytib0UzMmhvUVJuWDlFV04vZjB2SDZ6QS9ZS1R6cmpjYTZKUThnQVYxRXJ3dlJXRHB5TWN3ZFlDaVdBTHY5U2Nia0FjZWJPRTFzMUpjdFo1UkJYZ2dkWldyWWk3MlgrSTRpNldneVpjSUdhaS9yWjR2Mm90b1dBRUhTMHkxeWgxcVQ3TkRQcGwvTWNEYVRHa05VNkMrOFZmakQ3OERyVVhFY0FmS3ZQZ0tsS3JPTVpuRDFsQ0dzVmlpbUdZK0xTdUlkWTQ1TUxteWFhNVVUNEtXcGg2ZEE9PTwvZHM6U2lnbmF0dXJlVmFsdWU+DQogICAgICA8S2V5SW5mbyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+DQogICAgICAgIDxkczpYNTA5RGF0YT4NCiAgICAgICAgICA8ZHM6WDUwOUNlcnRpZmljYXRlPk1JSUM3akNDQWRhZ0F3SUJBZ0lRUnJqc2JGUGFYSWxPRzNHVHY1MGZrakFOQmdrcWhraUc5dzBCQVFzRkFEQXpNVEV3THdZRFZRUURFeWhCUkVaVElGTnBaMjVwYm1jZ0xTQlhVekl3TVRKU01pMHdMbk4zYVc1bWIzSnRaWEl1WTI5dE1CNFhEVEUwTURFeU1ERTFNVFkwTUZvWERURTFNREV5TURFMU1UWTBNRm93TXpFeE1DOEdBMVVFQXhNb1FVUkdVeUJUYVdkdWFXNW5JQzBnVjFNeU1ERXlVakl0TUM1emQybHVabTl5YldWeUxtTnZiVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLZStyTFZtWHkxUXdDd1p3cWdiYnAxLyszWld4ZDlUL2pWMGhwTElJV3IrTENPSHFxOG44YmVKdmxpdmdMbURKbzhmK0VJVG5BeFdjc0pVdlZhaS8zNUFoSENVcTl0YzlzcU1wNVBXdGFiQUVNYjJBVTcyL1FsWC83MkQyL05iR1FxMUJXWWJxVXBncENaMm5TZ3ZsV0RIbENpVW8vL1VHc3Zmb3gwMWtqVEZsbXFRSW5zSlZmUnhGNUFjQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaThjNkM0emFURWM3YVFpVWd2bkdRZ0NiTVpiaFVYWExHUnBqdkZMS2FRemt3YTllcTdXTEppYmNTTnlHWEJhL1NmVDV3SmdzbTNUUEtnU2VoR0FPVGlyaGNxSGhlWnl2Qk9iQVNjWTdHT1QrdTlwVllwNnJhRnJjN2V6M2MrQ0dIZVYvdE52eTFoSk5zMTJGWUg0WCtaQ05GSVQ5dHByaWVSMjVOQ2RpNVNXVWJQWkwwdFZ6SnNIYzF5OTJiMk0yRnhxUkRvaHhRZ0p2eUpPcGNnMm1TQnpaWklrdkRnN2dmUFNVWEhWUzFNUXMwUkhTYndxL1hkUW9jVVVobDkvZS9ZV0NiTk54bE04NEJ4RnNCVW9rMWRIL2d6QnlTeCtGYzh6WWk3Y09xOXlhQlQzUkxUNmNHbUZHVllaSlc0RnloUFpPQ0xWTnNMbG5QUWNYM2REZzlBPT08L2RzOlg1MDlDZXJ0aWZpY2F0ZT4NCiAgICAgICAgPC9kczpYNTA5RGF0YT4NCiAgICAgIDwvS2V5SW5mbz4NCiAgICA8L2RzOlNpZ25hdHVyZT4NCiAgICA8U3ViamVjdD4NCiAgICAgIDxOYW1lSUQgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDpwZXJzaXN0ZW50Ij5BQkNERUcxMjM0NTY3ODkwPC9OYW1lSUQ+DQogICAgICA8U3ViamVjdENvbmZpcm1hdGlvbiBNZXRob2Q9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpjbTpiZWFyZXIiPg0KICAgICAgICA8U3ViamVjdENvbmZpcm1hdGlvbkRhdGEgSW5SZXNwb25zZVRvPSJfMDQ5OTE3YTYtMTE4My00MmZkLWExOTAtMWQyY2JhZjliMTQ0IiBOb3RPbk9yQWZ0ZXI9IjIwMTQtMDEtMzFUMTU6NDE6MzEuMzU3WiIgUmVjaXBpZW50PSJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vbG9naW4uc3JmIiAvPg0KICAgICAgPC9TdWJqZWN0Q29uZmlybWF0aW9uPg0KICAgIDwvU3ViamVjdD4NCiAgICA8Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMTQtMDEtMzFUMTU6MzY6MzEuMjYzWiIgTm90T25PckFmdGVyPSIyMDE0LTAxLTMxVDE2OjM2OjMxLjI2M1oiPg0KICAgICAgPEF1ZGllbmNlUmVzdHJpY3Rpb24+DQogICAgICAgIDxBdWRpZW5jZT51cm46ZmVkZXJhdGlvbjpNaWNyb3NvZnRPbmxpbmU8L0F1ZGllbmNlPg0KICAgICAgPC9BdWRpZW5jZVJlc3RyaWN0aW9uPg0KICAgIDwvQ29uZGl0aW9ucz4NCiAgICA8QXR0cmlidXRlU3RhdGVtZW50Pg0KICAgICAgPEF0dHJpYnV0ZSBOYW1lPSJJRFBFbWFpbCI+DQogICAgICAgIDxBdHRyaWJ1dGVWYWx1ZT5hZG1pbmlzdHJhdG9yQGNvbnRvc28uY29tPC9BdHRyaWJ1dGVWYWx1ZT4NCiAgICAgIDwvQXR0cmlidXRlPg0KICAgIDwvQXR0cmlidXRlU3RhdGVtZW50Pg0KICAgIDxBdXRoblN0YXRlbWVudCBBdXRobkluc3RhbnQ9IjIwMTQtMDEtMzFUMTU6MzY6MzAuMjAwWiIgU2Vzc2lvbkluZGV4PSJfN2UzYzFiY2QtZjE4MC00Zjc4LTgzZTEtNzY4MDkyMDc5M2FhIj4NCiAgICAgIDxBdXRobkNvbnRleHQ+DQogICAgICAgIDxBdXRobkNvbnRleHRDbGFzc1JlZj51cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpQYXNzd29yZFByb3RlY3RlZFRyYW5zcG9ydDwvQXV0aG5Db250ZXh0Q2xhc3NSZWY+DQogICAgICA8L0F1dGhuQ29udGV4dD4NCiAgICA8L0F1dGhuU3RhdGVtZW50Pg0KICA8L0Fzc2VydGlvbj4NCjwvc2FtbHA6UmVzcG9uc2U+";
        SamlResponse samlResponse = new SamlResponse(settings, newHttpRequest(samlResponseEncoded));
	    String nameId = samlResponse.getNameId();
```
And was able to extract nameId
```
ABCDEG1234567890
```

Are you using latest version of java-saml?

**Comment by Surender-godara** [comment]
thanks for Quick response.i am using  java-saml 2.2.0 version.

okay i'll try update version and your suggestion. I'll get back to you.

**Comment by Surender-godara** [comment]
Hi Thanks,in updated version it works.
