### ISSUE TITLE
Signature validation failed. SAML Response rejected

### ISSUE THREAD

**Issue by sdivakarrajesh** [onelogin/java-saml#175]
I have checked this site

https://www.samltool.com/validate_response.php

and it shows "THE SAML RESPONSE IS VALID."
but still auth.isAuthenticated() returns false. I am using the sample code provided in the website and I have done all the steps mentioned.

The website shows that the user  has logged with correct timing. But in the sp app deployed in tomcat it says "Not Authenticated" with the red alert

**Comment by pitbulk** [comment]
Can you review the values of [auth.getErrors](https://github.com/onelogin/java-saml/blob/667c7d882277f770a2772d8eba61fce729869340/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L745)() and getLastErrorReason?

Can you verify the public cert is properly setup on the java-saml settings?

**Comment by pitbulk** [comment]
what about getLastErrorReason ?

**Comment by sdivakarrajesh** [comment]
That gives me "Signature validation failed. SAML Response rejected"

**Comment by pitbulk** [comment]
Yu will need to debug the [validateSign](https://github.com/onelogin/java-saml/blob/a005fd21736c032a944cb5692028753edee94493/core/src/main/java/com/onelogin/saml2/util/Util.java#L886) and the [validateSignNode](https://github.com/onelogin/java-saml/blob/a005fd21736c032a944cb5692028753edee94493/core/src/main/java/com/onelogin/saml2/util/Util.java#L964) method to get the real reason for the Signature invalidation.

**Comment by sdivakarrajesh** [comment]
Resolved it!

It was because i copy-pasted the sha fingerprint from the website dashboard to onelogin.saml2.idp.certfingerprint located in onelogin.saml.properties
i.e., i pasted the formatted fingerprint
The issue is overcame by pasting the non formatted fingerprint from [this site](https://developers.onelogin.com/saml/online-tools/x509-certs/calculate-fingerprint) without the colons

May be you could add this as a pointer in the [official tutorial](https://developers.onelogin.com/saml/java)

Thanks for the quick response though
