### ISSUE TITLE
Parse SP metadata XML and construct Saml2Settings out of it?

### ISSUE THREAD

**Issue by jaikiran** [onelogin/java-saml#177]
I am using 2.3.0 of the java-saml library. The usage/integration of this library has been seamless, so thank you for that.

One thing I'm missing right now is the ability to parse a SP metadata XML and construct a Saml2Settings out of it. Imagine doing something like below for IDP metadata XML:

```
final Map<String, Object> idpSettings = IdPMetadataParser.parseFileXML("idp-metadata.xml");
final Saml2Settings settings = new SettingsBuilder().fromValues(idpSettings).build();
```
What I would like is a similar API which allows one to parse XML content (string/file/url/inputstream) that represents the SP metadata and then allows that parsed output to be used in the construction of Saml2Settings. Is it currently possibly and I missed it? If not, can the library be enhanced to add such support?

**Comment by pitbulk** [comment]
> What I would like is a similar API which allows one to parse XML content (string/file/url/inputstream) that represents the SP metadata and then allows that parsed output to be used in the construction of Saml2Settings. 

The toolkit help to deploy a Service Provider, so we have tools to manage Identity Provider metadata only, to be registered on the settings.

I'm maybe misunderstanding something. Why do you want to generate SP settings from an SP metadata? How can be a SP related to an already working SP. I don't see the connection here.

**Comment by dhovart** [comment]
I suppose he meant "idp metadata".

**Comment by pitbulk** [comment]
But there is already an IdPMetadataParser and he already shared a way to build settings from the result of parsing IdP metadata.

**Comment by jaikiran** [comment]
Sorry, I forgot to reply to this.

>> The toolkit help to deploy a Service Provider, so we have tools to manage Identity Provider metadata only, to be registered on the settings.

Ok, I see what you mean and now realize that I'm using it for something this wasn't meant for. 

To give a bit more context, I was using the library in a place where the client of this library, although acts as a SP, didn't really know its runtime contextual details (like what's the ACS, SLO endpoints). Those details would be configured and stored in a datastore outside of this component. When a SSO based interaction (like initiating a logout) was supposed to take place, I was constructing an `Auth` instance by fetching the IDP and the SP details from that datastore. The datastore currently holds the IDP metadata as a XML. I was planning to do the same for the SP metadata and then have it parsed by this library as and when required. The alternatives for storing the SP metadata for me are:

- Store this as XML and then have a custom parsing within my application to create a Saml2Settings out of it.
- Store it in whatever other format and then use this library's SettingsBuilder constants to set them up myself. (I might end up doing this)

I hope these details help in understanding why I was looking for such an API.

**Comment by pitbulk** [comment]
ok, I don't gonna discuss your implementation, but you can understand that a SP parser is out of scope of that toolkit.

**Comment by jaikiran** [comment]
>> but you can understand that a SP parser is out of scope of that toolkit.

Yes, I understand. Thank you for the responses so far.

Closing this request.
