### ISSUE TITLE
v2.3.1 Java SAML build issue

### ISSUE THREAD

**Issue by rajeshmese** [onelogin/java-saml#183]
Im able to build java-saml-core and the jar is getting generated. Bu when in build the next one java-saml  im getting the below isse,

Failed to execute goal on project java-saml: Could not resolve dependencies for project com.onelogin:java-saml:jar:2.3.1-SNAPSHOT: Failed to collect dependencies at com.onelogin:java-saml-core:jar:2.3.1-SNAPSHOT: Failed to read artifact descriptor for com.onelogin:java-saml-core:jar:2.3.1-SNAPSHOT: Could not find artifact com.onelogin:java-saml-toolkit:pom:2.3.1-SNAPSHOT -> [Help 1]

please help to resolve

**Comment by srirampriyanka** [comment]
doesnt work!
