### ISSUE TITLE
Onelogin Replace Java Rest Service

### ISSUE THREAD

**Issue by rajeshmese** [onelogin/java-saml#184]
I'm Trying to implement onelogin for my application to replace the username password verification in back end mysql. Our application have below design,

UI(Angualr Js)----(REST Service)----> Java (Rest API) --> JDBC (My Sql).

Will it is possible to use the onelogin java saml  to integrate here with this application, i have seen the sample provided in java jsp. Please confirm if some one has hands on.

**Comment by pitbulk** [comment]
java-saml will add SAML support to your application.

If you want to authenticate users on 3rd party Identity SAML Provider instead use your local JDBC, then the answer is yes, you can use java-saml for that.

**Comment by rajeshmese** [comment]
Thanks.  Since we use Angular Js and connect Java REST Service for JDBC. So want to know if the Java SAML  project will support it?  I have seen sample Jsp file have called "Auth" class for login validation using http request and response. In our case we don't have those, and we can't do this in Angualr JS. So want to know if we can call this "Auth" in Java file by making rest call from Angular  Js?

**Comment by pitbulk** [comment]
It can be done, but with the inclusion of Oauth2 or OIDC.

See https://github.com/slem1/saml-angular
