### ISSUE TITLE
com.onelogin.saml2.util.Util - Load XML error

### ISSUE THREAD

**Issue by dswitzer** [onelogin/java-saml#191]
Working on implementing the OneLogin Java Toolkit into an existing web application and I'm running into an issue with the `XPathFactory.newInstance()` calls throwing the following exception:

```
com.onelogin.saml2.util.Util - Load XML error: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/opt/coldfusion10/cfusion/lib/saxon9he.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/opt/coldfusion10/cfusion/lib/saxon9he.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
        at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102) ~[na:1.8.0_161]
        at com.onelogin.saml2.util.Util.parseXML(Util.java:361) ~[na:na]
        at com.onelogin.saml2.util.Util.convertStringToDocument(Util.java:304) ~[na:na]
        at com.onelogin.saml2.util.Util.loadXML(Util.java:166) ~[na:na]
        ... cropped ...
```

In looking into the issue, I could resolve the problem by adding the following JVM argument to my jvm.config file:

```
-Djavax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom=com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl
```

However, since this could have other side effects I'm looking for a better method to solve the issue.

In looking at the Util.java source, I was able to resolve the problem by adding the following helper function and then using it to initialize new instances of the XPathFactory:

```
private static XPathFactory getXPathFactory() {
	try {
		return XPathFactory.newInstance(XPathFactory.DEFAULT_OBJECT_MODEL_URI, "com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl", java.lang.ClassLoader.getSystemClassLoader());
	} catch (XPathFactoryConfigurationException e) {
		LOGGER.debug("Error generating XPathFactory instance: " + e.getMessage(), e);
	}

	return null;
}
```

Is there any issue with updating the code to be explicit about how the XpathFactory should configure an instance?

What *should* the be the correct `XPathFactoryImpl` to use?

If I generated a pull request for the change, would this be something that would be accepted?

**Comment by pitbulk** [comment]
It seems the issue you mention is specific to Saxon

Reference: https://saxonica.plan.io/issues/1944

**Comment by dswitzer** [comment]
It probably is, but I can't upgrade the version of Saxon safely (it's comes in the distribution of our application server) without potentially breaking things. I tried loading the new version of Saxon in class loader, but it appears the original version is getting picked up by `java-saml-core-2.3.1-SNAPSHOT.jar`.

That's also my fear in setting the `-Djavax.xml.xpath.XPathFactory` argument for the JVM. I'm worried that changing the default class might result in things breaking throughout this large legacy application.

That's why I was looking to change the Util source to be explicit about the implementation to use. 

Seems like if the Util.java isn't explicit about the XpathFactory to use, it could lead to issues where it might be using a default that's not expected and that could cause issues in some environments.

If the code was explicitly about the XPathFactory implementation to use, then this could avoid problems for other users as well.

**Comment by pitbulk** [comment]
I see, then its ok to provide a solution for that.

Please provide a PR

**Comment by dswitzer** [comment]
@pitbulk 

I've created the pull request. It's passing all CI tests.
