### ISSUE TITLE
Multi-tenant support 

### ISSUE THREAD

**Issue by rakeshshete** [onelogin/java-saml#193]
Looking at the library and APIs, are there any known restrictions/limitations if its used for a multi-tenant SaaS app that requires to integrate with multiple IdPs with the SaaS app as single service provider?

**Comment by pitbulk** [comment]
No limitation.

The way to implement the tenant is not hard.

Based on the example provided, you will need a way to identify each tenant at the endpoints.
1 possible way is by subdomains or subpaths, the other is by an additional GET parameter.

Once you know what is the tenant, you can load its specific SAML settings and execute the SAML flow.

**Comment by rakeshshete** [comment]
Gr88! That's how I plan to use the library.
