### ISSUE TITLE
Does onelogin.saml2.debug really do anything?

### ISSUE THREAD

**Issue by dswitzer** [onelogin/java-saml#194]
Maybe I'm missing something obvious, but I don't see where `onelogin.saml2.debug` actually does anything within the core code. I thought this was controlling the logging level, but that doesn't appear to be the case. 

In tracing the code, it gets mapped to the private `Saml2Settings.debug` variable, which makes `Saml2Settings.isDebugActive()` return `true` or `false` based on the setting, but I don't see any of the code that actual does anything with this information.

The only place it used is in the `acs.jsp` to determine how to show errors.

Is that the only thing it's used for?

**Comment by pitbulk** [comment]
Is an internal setting of the toolkit.

And the way to use it is with the isDebugActive as you saw on acs.jsp as a way decide when to show (for debugging) the reason for SAML Messages invalidation.

**Comment by dswitzer** [comment]
Thanks for the information.

When I saw the setting in the INI file, it felt like it was controlling the logging output. It might be worth noting in the INI file the debug setting does not affect logging and is simple a boolean to affect your own implementation of the API.

**Comment by tylerrstevens** [comment]
Sorry, is there something that I need to do, in addition to this to get the debug output?  

# Enable debug mode (to print errors)
onelogin.saml2.debug =  true

I'm running the SAML Java examples in Apache Tomcat 9.0.98 and I receive the following error.  When I make the config change above, restart Tomcat, reproduce the issue, I see no additional debug in any logs? 

com.onelogin.saml2.exception.ValidationError: SAML Response could not be processed
	com.onelogin.saml2.authn.SamlResponse.loadXmlFromBase64(SamlResponse.java:160)
	com.onelogin.saml2.authn.SamlResponse.<init>(SamlResponse.java:118)
	com.onelogin.saml2.authn.SamlResponse.<init>(SamlResponse.java:139)
	com.onelogin.saml2.factory.SamlMessageFactory.createSamlResponse(SamlMessageFactory.java:55)
	com.onelogin.saml2.Auth.processResponse(Auth.java:1204)
	com.onelogin.saml2.Auth.processResponse(Auth.java:1253)
	org.apache.jsp.acs_jsp._jspService(acs_jsp.java:160)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:376)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:324)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

Thanks!

**Comment by jarretttaylor** [comment]
@tylerrstevens I believe you want to configure the "com.onelogin" logger in whatever logging framework you use. For example, this is my configuration for logback:

`<logger name="com.onelogin" level="trace" />`
