### ISSUE TITLE
LogoutResponse requires signing event though logout response signing is turned off

### ISSUE THREAD

**Issue by mhjort** [onelogin/java-saml#196]
When you set:
`onelogin.saml2.security.logoutresponse_signed` to `false` the signing is still checked if `onelogin.saml2.security.want_messages_signed` is set to `true`.

Here is the code related to LogoutResponse validation. 
https://github.com/onelogin/java-saml/blob/909a8c07f9087b5e124e4768ea99fe1dc188b88c/core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java#L226

It will not use `onelogin.saml2.security.logoutresponse_signed` property here. We are using Auth0 and we we would like to have a setup where login response related messages and responses are signed. However, we do not want to sign logout response (it is not even possible in Auth0). It seems this setup is impossible with current version of tool. Or maybe I have misunderstood these settings somehow?

**Comment by pitbulk** [comment]
**onelogin.saml2.security.logoutresponse_signed**

Indicates whether the <samlp:logoutResponse> messages sent by this SP will be signed.

**onelogin.saml2.security.want_messages_signed**

Indicates a requirement for the <samlp:Response>, <samlp:LogoutRequest> and
<samlp:LogoutResponse> elements received by this SP to be signed.

The toolkit allows you to require or not Signature on SAML Messages sent by the IdP and also enable or disable the signing SAML Messages generated by the SP.

**Comment by mhjort** [comment]
Ok. Makes sense. I was wondering if there is a way to sign login response message but skip logout response signing. Apparently this is not possible.

**Comment by pitbulk** [comment]
"sign login response message". 

The Login SAMLResponse is signed by the IdP. You can require it by 
```
onelogin.saml2.security.want_messages_signed = true
```

"skip logout response signing"

If you don't want that the SP sign the logout responses, then set:
```
onelogin.saml2.security.logoutresponse_signed = false
```

If you don't want to validate logout responses signatures at SP, then you need to set 
```
onelogin.saml2.security.want_messages_signed = false
```
but as you saw, that conflicts the signature validation of SAMLResponse messages that we detailed before
