### ISSUE TITLE
Question for implement SAML Toolkit code for ADFS SLO (as well as onelogin) in my application

### ISSUE THREAD

**Issue by niravravalhighq** [onelogin/java-saml#199]
Hi @pitbulk ,
I have already developed SSO application in java with openSAML2.2.2 Jar.
Now I need to make improvement for implement SLO in this application.

And I am new in SLO things. So I just refering some code for it and found your SLO implementation.

**The question is** 
Can I use SLO implementation found in toolkit in my application? Because In your case, I was not found any ADFS related properties or configuration?

Please guide in this case,

Thanks.

**Comment by pitbulk** [comment]
Yes, you can use the toolkit to implement SSO/SLO with ADFS.

**Comment by niravravalhighq** [comment]
Thanks for quick response @pitbulk .
Going forward, if I face any issues/ queries then can I post same here?

**Comment by pitbulk** [comment]
Sure.

**Comment by niravravalhighq** [comment]
Thanks @pitbulk 
You can close this issue as of now.
