### ISSUE TITLE
Consider Java8 and/or jodatime exclusion

### ISSUE THREAD

**Issue by magott** [onelogin/java-saml#201]
While the motives for sticking with Java 7 compatibility outlined in #67 are honorable it comes at a cost for java-saml adopters using Java 8+. 

Java-saml depends on Joda-time, which is/used to be a fine framework for application developers, isn't really suited for inclusion in a library such as java-saml. It will put joda-time on the classpath of adopters, many of whom don't need or want it in their stack. Since the release of Java 8 in 2013 JSR 310 (the new time and date api) has been the preferred date api for developers. The inclusion of similarly named types from jodatime in java 8+ apps is a code smell.

Java 7 is no longer supported by Oracle. The JDK7 download page comes with a warning:
```WARNING: These older versions of the JRE and JDK are provided to help developers debug issues in older systems. They are not updated with the latest security patches and are not recommended for use in production.```

Why should a library such as java-saml cater to users running their apps on an insecure platform?

Should you still not feel able to drop java 7 support, I encourage you to remove joda-time, instead using the standard date api in java pre v8. As horrible as it is ,at least you won't impose joda-time on most of your adopters, which I assume are on java 8+

Alternatively, introduce a 3.0 branch, for java 8+? It is not uncommon, and done by HikariCP amongst others https://github.com/brettwooldridge/HikariCP

**Comment by pitbulk** [comment]
Ok, I think we will need to go for a new 3.0 branch only java 8+ compliant.

I plan to release soon a new release of java-saml, after it, we can work on the 3.0 branch.

**Comment by magott** [comment]
Cool. Let me know if you need help

**Comment by chenrui333** [comment]
Do you have any updates of bumping the library to work with Java8+? Thanks!

**Comment by pitbulk** [comment]
We made 2.5.0 only compatible with Java7 and Java8
