### ISSUE TITLE
Validate Auth Request 

### ISSUE THREAD

**Issue by altounsi** [onelogin/java-saml#207]
I know there is a validation for SAML response, however, is there is a way to validate SAML Request using JAVA,

**Comment by pitbulk** [comment]
The java-saml toolkit allow you deploy a Service Provider so, it validates messages sent by the IdP:
 - SAMLResponse
- LogoutRequest
- LogoutResponse

So there is no code to validate AuthNRequest.

**Comment by altounsi** [comment]
I am not SP, and I am not IdP also, I am just in the middle between both, so the SP sends to me and I have to validate the AuthNRequest and if it is valid if just forward it. any suggestions. I can do it using WSO2 but it is too heavy, i just need this functionality from oneLogin api or any other something like this [https://www.samltool.com/validate_authn_req.php ](url)

**Comment by altounsi** [comment]
Do you have this feature in the paid solution.

**Comment by pitbulk** [comment]
There is no paid version of the java-saml toolkit.

It implements the SP, not the IdP

**Comment by ClaudioConsolmagno** [comment]
As I understand, you could do the following checks that use `com.onelogin.saml2.util.Util`:
```java
Util.validateXML(document, SchemaFactory.SAML_SCHEMA_PROTOCOL_2_0)
Util.validateSign(document, certificate, null, null, '/samlp2:AuthnRequest/ds:Signature')
```
