### ISSUE TITLE
SamlResponse ID really required?

### ISSUE THREAD

**Issue by slorber** [onelogin/java-saml#208]
Hi,

I have a very large corp SAML IdP which need to send me SamlResponse for SSO. 
The workflow is Idp initiated and there's no AuthN request. 

The response they send me does not contain any ID:
```xml
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://url-debranchement-exemple/exmple" IssueInstant="2019-01-11T12:41:35.113Z" Version="2.0"">
```
I'm not a SAML expert but is it normal this library enforces the presence of an ID?

According to this tool [https://www.samltool.com/validate_xml.php](https://www.samltool.com/validate_xml.php), it seems the ID is required

This is also what I understand from the XSD https://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd

![image](https://user-images.githubusercontent.com/749374/51202236-914ccc80-18fe-11e9-8dd5-4eb035af5d81.png)

Is there a way to disable this ID check in the lib? 
What's the purpose of this ID exactly? I can't find any info about it

**Comment by pitbulk** [comment]
The ID is mandatory as you can see here as well:
http://www.datypic.com/sc/saml2/e-samlp_Response.html

Think that the signature, if the SAMLResponse is signed, will use that ID as the reference to identify what element was signed.
