### ISSUE TITLE
Certs folder location

### ISSUE THREAD

**Issue by kevinkarwaski** [onelogin/java-saml#209]
In the comments of the example java properties file, there is mention that the x509 cert and private key of the SP are usually referenced as files in a certs folder.

Can you clarify exactly where on the filesystem the certs / certs folder should exist? When using flat files, should the values of the `onelogin.saml2.sp.x509cert` and `onelogin.saml2.sp.privatekey` properties be left unassigned?

Any clarity on how the cert files / folder is meant to be implemented would be greatly appreciated, thanks.

https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties#L40-L47

**Comment by pitbulk** [comment]
Initially, there was a plan to support key/certs defined on [filesystem](https://github.com/onelogin/java-saml/issues/54) as well as [support keystore](https://github.com/onelogin/java-saml/issues/55) but the features were never implemented.

**Comment by GregoireDucharme** [comment]
Thank you Kanye, very cool
