### ISSUE TITLE
Support signatures

### ISSUE THREAD

**Issue by jrowny** [onelogin/java-saml#21]
Currently this library won't work with any providers who require signed auth requests. Supporting signed requests is pretty easy, but you must also add the "destination" to the root of the request XML. You can see my implementation here: https://github.com/jrowny/java-saml/blob/master/src/com/onelogin/saml/AuthRequest.java

**Comment by pitbulk** [comment]
The [2.0.0](https://github.com/onelogin/java-saml/tree/v2.0.0) support signatures:
* [AuthNRequest](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/Auth.java#L189)
* [LogoutRequest](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/Auth.java#L240)
* [LogoutResponse](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/Auth.java#L385)
