### ISSUE TITLE
Null Pointer exception within Saml core library when trying to process Saml Response from IDP

### ISSUE THREAD

**Issue by satyagh2803** [onelogin/java-saml#217]
Hello, I am getting Null pointer exception within saml core library "SamlResponse.java" when trying to process Saml Response from IDP.
Getting exception at the line "assertionNode.getParentNode().getParentNode().replaceChild(assertionNode, assertionNode.getParentNode());" from below method. Before invoking this method, I see that the document that is being passed to this method is printing as "[Document # null]" but it did not go into if block which checks for null value and proceed to further steps of the code.
Please help. I am in dire need of some suggestion to get my SSO application working.

private Document decryptAssertion(Document dom) throws XPathExpressionException, ParserConfigurationException, SAXException, IOException, SettingsException {		
		PrivateKey key = settings.getSPkey();
		if (key == null) {
			throw new SettingsException("No private key available for decrypt, check settings", SettingsException.PRIVATE_KEY_NOT_FOUND);
		}

		NodeList encryptedDataNodes = Util.query(dom, "/samlp:Response/saml:EncryptedAssertion/xenc:EncryptedData");
		Element encryptedData = (Element) encryptedDataNodes.item(0);
		Util.decryptElement(encryptedData, key);

		// We need to Remove the saml:EncryptedAssertion Node
		NodeList AssertionDataNodes = Util.query(dom, "/samlp:Response/saml:EncryptedAssertion/saml:Assertion");
		Node assertionNode = AssertionDataNodes.item(0);
		assertionNode.getParentNode().getParentNode().replaceChild(assertionNode, assertionNode.getParentNode());
		// In order to avoid Signature Validation errors we need to rebuild the dom.
		// https://groups.google.com/forum/#!topic/opensaml-users/gpXvwaZ53NA
		String xmlStr = Util.convertDocumentToString(dom);
		Document doc = Util.convertStringToDocument(xmlStr);
		// LOGGER.debug("Decrypted SAMLResponse --> " + xmlStr);
		return doc;
	}

Thanks & Regards,
Satya.

**Comment by ahjohannessen** [comment]
Seems like the certificate used to sign is not what you have a private key for. Either the response uses a different certificate or your configured certificate does not match up with your private key.
