### ISSUE TITLE
Toolkit does not exposesubStatusCode

### ISSUE THREAD

**Issue by pelaxa** [onelogin/java-saml#218]
Hi,

There does not seem to be an easy way to grab the substatuscode of the response when using the toolkit.  Without this, it is hard to understand why the response returned a failure.

Suggest adding the statuscode and substatuscode to the list of errors so that they can be examined/displayed, etc.

**Comment by pitbulk** [comment]
Substatus is supported
- https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/model/SamlResponseStatus.java#L18
- https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java#L1412

But I think you mean that [checkStatus](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L583) methods of SAMLResponse and Logout should expose that info as well right?

Do you have a PR?

**Comment by pelaxa** [comment]
I updated the source to expose these through the errors list as I suggested.  I can create a pull request for that, but was not sure if this was the best way to expose them or not.

I'll create one by end of day hopefully.

**Comment by pitbulk** [comment]
Please share and I willl review.

I think make sense if there is a Substatus Code to expose it as well and be part of the error message.
