### ISSUE TITLE
SamlResponse signature SHA256-RSA validation fails with unexpected signature length

### ISSUE THREAD

**Issue by kherrala** [onelogin/java-saml#222]
Steps to produce:
- IDP metadata contains two IDP X509 certificates with different RSA key lengths 2048 vs. 3072 bits because certificate transition is about to happen in future. Signature algorithm is SHA256-RSA.
- Use onelogin.saml2.idp.x509certMulti property to configure both certificates.
- Process SAML login redirect using com.onelogin.saml2.Auth.processResponse()
- Authentication response validation fails while comparing XML signature using the 3072 bit key. The error stack trace contains the message: 
`Signature length not correct: got 256 but was expecting 384`
- Second X.509 certificate is never checked against received XML signature.

Expected behaviour:
- Signature validation should continue past the first signature verification failure using 3072 bit key. 
- Second IDP X.509 certificate validation should succeed with 2048 bit key.

Wrong signature length exception is an expected condition due to transitioning to longer RSA key length.

Full stacktrace:

```
com.onelogin.saml2.util.Util - Error executing validateSignNode: Signature length not correct: got 256 but was expecting 384
org.apache.xml.security.signature.XMLSignatureException: Signature length not correct: got 256 but was expecting 384
	at org.apache.xml.security.algorithms.implementations.SignatureBaseRSA.engineVerify(SignatureBaseRSA.java:92)
	at org.apache.xml.security.algorithms.SignatureAlgorithm.verify(SignatureAlgorithm.java:301)
	at org.apache.xml.security.signature.XMLSignature.checkSignatureValue(XMLSignature.java:760)
	at org.apache.xml.security.signature.XMLSignature.checkSignatureValue(XMLSignature.java:697)
	at com.onelogin.saml2.util.Util.validateSignNode(Util.java:1010)
	at com.onelogin.saml2.util.Util.validateSign(Util.java:931)
	at com.onelogin.saml2.authn.SamlResponse.isValid(SamlResponse.java:301)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:640)
	at com.onelogin.saml2.Auth.processResponse(Auth.java:673)
```

**Comment by pitbulk** [comment]
Thanks for reporting that, do you have a PR to solve this?

**Comment by sunkaiqin** [comment]
@kherrala Do you use **Dynamic Settings** to configure your SAMLSettings? if so, when configuring **IDP_X509CERTMULTI_PROPERTY_KEY** you need this line of code to put your certs into it: 
                ```
// OneLogin uses onelogin.saml2.idp.x509certMulti.(index) to lookup the additional IdP certificates.
samlData.put(IDP_X509CERTMULTI_PROPERTY_KEY + "." + (i - 1), idpCerts.get(i));
```
Then your second cert could be looked up.

**Comment by kherrala** [comment]
@sunkaiqin Thank you and sorry for the false alarm! I am using dynamic properties and it seems I was just concatenating certs using the comma-separator because that is how all other list-valued properties work. 

Somehow I was distracted by the stack trace printed by Util.validateSignNode() exception handler. Maybe only the expected 
org.apache.xml.security.signature.XMLSignatureException validation failure should be caught and logged without stack trace?
