### ISSUE TITLE
SLO with ADFS - Signature validation failed

### ISSUE THREAD

**Issue by GeoffMcLennan** [onelogin/java-saml#225]
Hi, I'm having an issue integrating the SSO API I created using the java-saml library with an ADFS IdP.

So far IdP initiated login is working fine, but when I try IdP initiated logout the signature is unable to be validated. I have double checked the algorithm matches for both the incoming LogoutRequest and the certs (SHA256withRSA).

I've noticed one thing that looks slightly different than other examples. The payload to initiate SLO is a get request with query parameters in the format: 
`?SAMLRequest={encoded request}&Signature={signature}&SigAlg=http%3a%2f%2fwww.w3.org%2f2001%2f04%2fxmldsig-more%23rsa-sha256`

The signature is passed as a query parameter from ADFS, not as part of the SAMLRequest XML payload. Is this correct/acceptable from the standpoint of SAML compatibility? Or could this be causing the signature to appear invalid.

The Logout Request payload: 
```xml
<samlp:LogoutRequest Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
    Destination="https://sp-domain.com/sso/slo/dev03"
    ID="_f7cb9bf9-579d-449e-a90c-749f34e5c26a" IssueInstant="2019-03-14T00:40:39.039Z"
    NotOnOrAfter="2019-03-14T00:45:39.039Z" Version="2.0"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://idp-domain.com/adfs/services/trust</Issuer>
    <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
        xmlns="urn:oasis:names:tc:SAML:2.0:assertion">g.mclennan@idp-domain.com</NameID>
    <samlp:SessionIndex>_cba24e00-c636-4985-8f78-aa11a2bbc512</samlp:SessionIndex>
</samlp:LogoutRequest>
```

I'm at a loss on how to get this working. I have checked the encoding of all the inputs to the library and everything seems to be ok, but the library still seems to think the signature is invalid. Any advice?

**Comment by pitbulk** [comment]
Yes, in the HTTP-Redirect binding, the Signature is not part of the XML, and instead, a GET parameter.

What error do you get and in what side?

**Comment by GeoffMcLennan** [comment]
getLastErrorReason returns `Signature validation failed. Logout Request rejected` and the returned list of errors just contains `invalid_logout_request`.

This is on the SP side during IdP initiated logout, I am trying to handle the incoming LogoutRequest from the IdP with processSLO and this is the error I'm getting.

**Comment by pitbulk** [comment]
Can you try to verify the same Message at https://www.samltool.com/validate_logout_req.php?

**Comment by GeoffMcLennan** [comment]
Yes it gets the same message there.

**Comment by pitbulk** [comment]
Maybe ADFS uses more than 1 certificate and is signing with a different pair than the one registered on the SP?

**Comment by GeoffMcLennan** [comment]
I'm using IdPMetadataParser.parseRemoteXML to load the ADFS endpoints and certs, does that mean this method is missing some of the certs? Do I need to manually grab a certain cert to handle this use case with ADFS?

**Comment by GeoffMcLennan** [comment]
Curiously, the signature is successfully validated in the ACS request, so I'm thinking the issue is somewhere between the request and the input to the processSLO call. My API is in an AWS Lambda function behind an API Gateway, so I have a custom implementation of the HttpServletRequest that maps the input to my function to the format the java-saml library expects. Perhaps I have the encoding wrong somewhere in my implementation.

I see that it's the Util.validateBinarySignature in LogoutRequest.isValid() that is performing the validation. 
The first parameter, `signedQuery` is composed by calls to request.getEncodedParameter which parses the output of the HttpServletRequest.getQueryString() method. My implementation of this method returns the full URL encoded queryString i.e. `SAMLRequest={base64 encoded request}&Signature={signature}&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256`
One thing I notice here, is that when the isValid method assembles the signedQuery parameter, it does not add the Signature query param, so the input to the validateBinarySignature method is `SAMLRequest={base64 encoded request}&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256`. I am not super knowledgeable about validating signatures, so I assume this is intentional.

The signature parameter (before validateBinarySignature base64 decodes it) gets its value from HttpServletRequest.getParameterMap(). My implementation returns a Map<String, String[]> of all parameters (query and body). These are URL decoded but not base64 decoded. Before decoding, my signature looks like this: `oBtVRa8PhCmtAKBBuW5e1wIwqcdCb5l5qB/Ei4AYlXGT2xaZJ8rM0uPQrpqLoR5ALPptIAyZSq4k8zPpYYVEMEMs3lmmLMn4FYZVH6E/IkrvcTqFp6YaqKbhO4hO016qPx7h3jM6wzBmDNuYldM5/RA8PXMhpGbM7SXFNr3lPfWpPX+STjvXAEvt0OrzJLBuVprP4VRUye5yXQ9sFNiWbp1/GrXoiF7vvos1x4G+9rbjR728olQT+4qw+tMcQPVYQstTaUGV/CBcooaf8RDP5RlFqARowAuJlNDLXyoiGb1ZLomcJs5xpzBODU/XZ4UVLFVkBete/4qqkaMOqke5jQ==` and after decoding it is an unreadable string. I thought this might mean that my signature is already somehow base64 decoded, but if I remove the decoding in the input to validateBinarySignature, it still fails the validation.

The certList doesn't seem to have any problems (my IdP provides a signing and encryption cert and they're both there) and the sigAlg is `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256` which successfully gets translated to `SHA256withRSA`.

I'm still not sure where the error here is, although it would seem to be a problem in the input to the validation function all of the above input seems correct. Any ideas? Or does any of the above look wrong to you?

**Comment by pitbulk** [comment]
Now that you mention that you have your custom implementation...

Some ADFS versions uses lowercase Urlencoding. Maybe the issue is related to that fact.

**Comment by GeoffMcLennan** [comment]
Yup, that definitely looks like it may be the case. Our ADFS test server is running Windows Server 2019 and looking at the http request, I see a lot of lowercase hex in the URL encoded payload.

Any suggestions on how to handle this? Unfortunately, API gateway already decodes the query parameters before they reach my code, so I can't tell what case the URL encoded version was in. I'm guessing my only option is to have a user specified setting and lowercase the hex in any URL encoding?

**Comment by pitbulk** [comment]
See https://github.com/onelogin/java-saml/commit/e1a9d0957ae98d9de62000b37a06b52b0bf3e661

**Comment by GeoffMcLennan** [comment]
Unfortunately API Gateway/Lambda does not pass the raw query string to my program, it passes a map of the query string parameters that has already been URL decoded so I have no way of seeing if there is any non-canonical encoding in the original request. My implementation of HttpServletRequest constructs the query string when needed, but uses the default uppercase URL encoding.

Right now I think my only option is to have the user specify the encoding when they set up SSO with our applications unfortunately.

According to [this documentation in the python3](http://pydoc.net/python3-saml/1.2.6/onelogin.saml2.utils/) version of the library, this behavior started with ADFS 3.0, does that seem correct? I'll want to add that to my documentation.

**Comment by pitbulk** [comment]
I detected it on ADFS 3.0, but not sure if issues started with that version or there is some setting on ADFS that controls the urlencoding mechanism.

**Comment by GeoffMcLennan** [comment]
Ok, I'll do some digging on my end to see if there is a setting in ADFS but I'm not holding my breath for that.

I think as far as a work around goes, I'll just catch the signature validation error and retry it with the lowercase url-encoded query string so I don't need to introduce any new settings on our end. Not the most efficient solution but it should work.

Thanks very much for your help! I don't think I would have found that otherwise.

**Comment by Tuty-Kumaran** [comment]
Signature validation is getting failed for the ADFS IdP initiated Logout request. HTTP-POST is working fine. But HTTP-Redirect requests getting failed due to the signature validation. Tried the same to get the encoded data from the query string it doesn't work for me.
