### ISSUE TITLE
Signature required even if onelogin.saml2.strict set to false

### ISSUE THREAD

**Issue by jinta** [onelogin/java-saml#226]
The documentation regarding the **strict** property implies that in the case that it's set to false it will accept unsigned or unencrypted messages:
```
#  If 'strict' is True, then the Java Toolkit will reject unsigned
#  or unencrypted messages if it expects them signed or encrypted
#  Also will reject the messages if not strictly follow the SAML
onelogin.saml2.strict =  false
```
However, in the SamlResponse (outside the settings.isStrict check) the following still requires one to have a signature otherwise it throws the no signature validation exception:
https://github.com/onelogin/java-saml/blob/db6c5acdeb855d37272e822f946d9a055da7d7d9/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L283

Am I missing something?

Thanks

**Comment by pitbulk** [comment]
The documentation refers to the flags:
```
onelogin.saml2.security.want_messages_signed
onelogin.saml2.security.want_assertions_signed
onelogin.saml2.security.want_assertions_encrypted
onelogin.saml2.security.want_nameid_encrypted = false
```

Response or Assertion must be signed, even if the 'strict' property is set false.

**Comment by denistarnam** [comment]
Would it be possible to introduce a flag that would allow responses to pass through unsigned?

**Comment by pitbulk** [comment]
@denistarnam accepting an unsigned SAMLResponse is like accepting any password in a login form, makes no sense.

**Comment by denistarnam** [comment]
You're absolutely correct, that completely slipped my mind. Thank you for the clarification @pitbulk.
