### ISSUE TITLE
JAR file to sign Authn Request XML file

### ISSUE THREAD

**Issue by plaidshirtakos** [onelogin/java-saml#227]
I have predefined unsigned Authn Request XMLs, which should be signed from Java or Groovy code. I am looking for functionality of this online tool: https://developers.onelogin.com/saml/online-tools/validate/saml-authnrequest

**Comment by pitbulk** [comment]
This toolkit acts as a Service Provider, so it does not validate AuthNRequest.

But you can review how it validates LogoutRequest/LogoutResponse that are similar and do the same.

**Comment by plaidshirtakos** [comment]
@pitbulk : Is the linked tool's source available in any forms?

**Comment by nsidhaye** [comment]
@plaidshirtakos : I guess this should treat as simple Signed XML. This might be useful. https://docs.oracle.com/javase/6/docs/technotes/guides/security/xmldsig/XMLDigitalSignature.html#wp511745

**Comment by plaidshirtakos** [comment]
@nsidhaye : I found this question on SO about this, but not sure, how to use it with a predefined XML content: https://stackoverflow.com/questions/12528667/xml-digital-signature-java
