### ISSUE TITLE
Is there a mechanism to create, sign and encrypt a SAMLResponse

### ISSUE THREAD

**Issue by mwoodland** [onelogin/java-saml#228]
We've used the java-saml library to implement our SP and ACS endpoint.

We're now trying to write some UI/integration tests.

We think we need to dynamically generate the SAML response to send to our ACS since the URL will vary depending on where the test is being run.

We've got as far as dynamically generating a signed SAMLResponse using the Util class and everything is working perfectly:
``` Java
        final Document document = Util.loadXML(saml); //loads string to document

        final X509Certificate cert = Util.loadCert(PUBLIC_KEY_CERT);
        final PrivateKey privateKey = Util.loadPrivateKey(PRIVATE_KEY_PEM);

        final String signedResponse = Util.addSign(document, privateKey, cert, null);

        final String encodedSamlResponse = Base64.getEncoder().encodeToString(signedResponse.getBytes());
```

But now we want to extend our test to encrypt the SAML assertion. Unfortunately there doesn't appear to be any mechanism in the Util class to do this.

The OpenSAML library appears to be able to do this, but the library is no where near as nice and simple to use as the java-saml library (hence why we're using the java-saml library for our SP). It might also be possible for us to use the Apache Santuario XML security library to do this.

I was just wondering if there is an easy way to do this? Ideally using the java-saml library. Any help is much appreciated, thanks.

**Comment by pitbulk** [comment]
java-saml covers the SP part, not the IdP part so there is no way to generate SAMLResponse here.

**Comment by mwoodland** [comment]
Thanks for the help.

**Comment by kliaoLD** [comment]
Hello, i have the same situation.  I need to sign and encrypt a SAML response. Using the OneLogin Java library, I was able to do the former (sign). The library doesn't explicitly do the latter (encrypt). I tried the solution above, with some modifications for my situation, but generated a defective encrypted response that cannot be decrypted. The response has the right looking format, and it is valid as a valid XML. My code looks like below. Can you please point out where in my encryption steps i went wrong?  Thank you.


String SymCertFileName = "test-cert.pem";

String SymCertcontents = new 
String(Files.readAllBytes(Paths.get(SymCertFileName)));
        X509Certificate SymCert = Util.loadCert(SymCertcontents);

Document signedDocument = Util.loadXML(newsignedresp);  // from step 1


Key symmetricKey = Util.generateSymmetricKey();

// cipher for encrypt the data
XMLCipher xmlCipher = XMLCipher.getInstance(Constants.AES256_CBC);
        xmlCipher.init(XMLCipher.ENCRYPT_MODE, symmetricKey);

// cipher for encrypt the symmetric key
XMLCipher keyCipher = 
XMLCipher.getInstance(Constants.RSA_OAEP_MGF1P);
        keyCipher.init(XMLCipher.WRAP_MODE, 
SymCert.getPublicKey());

// encrypt the symmetric key
EncryptedKey encryptedKey = keyCipher.encryptKey(signedDocument, 
symmetricKey);


EncryptedData encryptedData = xmlCipher.getEncryptedData();
        KeyInfo keyInfo = new KeyInfo(signedDocument);
        keyInfo.add(encryptedKey);
        encryptedData.setKeyInfo(keyInfo);

Element signedAssertion = 
signedDocument.getElementById("signed_assertion");  


signedAssertion.removeAttribute("Version");
signedAssertion.removeAttribute("ID");
signedAssertion.removeAttribute("IssueInstant");

Document encryptedResult = 
xmlCipher.doFinal(signedAssertion.getOwnerDocument(), 
signedAssertion, false);
