### ISSUE TITLE
Fingerprint check in Util class is case sensitive

### ISSUE THREAD

**Issue by metalcarratt** [onelogin/java-saml#232]
The Util#validateSignNode uses the ``equals`` method to compare the stored fingerprint with the calculated fingerprint from the signature. If someone (me) were to use the wrong case (upper case) in the properties file for the ``onelogin.saml2.idp.certfingerprint`` setting they may be confused as to why the fingerprint validation fails.

I think replacing ``equals`` with ``equalsIgnoreCase`` would easily solve this problem.

**Comment by pitbulk** [comment]
Makes sense, do you have a PR?

**Comment by metalcarratt** [comment]
I checked out the code and created a branch but don't have permission to push. Do I need someone to give me permission, or should I be doing things differently?

Also, I was also unable to build the code using 'mvn clean install' from the command line as the unit tests were failing (before applying my change).  After applying the change I did run the UtilsTest in eclipse and it passed.

**Comment by pitbulk** [comment]
You need to clone the repo, create your own branch, push the branch in your repo and then you will be able to create the PR.

Related to the issue with mvn install, the latest build pass
https://travis-ci.org/onelogin/java-saml/builds/515243328
so no idea what are you experiencing in your local.
