### ISSUE TITLE
Multiple url to be configured in onelogin

### ISSUE THREAD

**Issue by abhi68** [onelogin/java-saml#236]
Hi ,
I have a requirement where we have an application that is having 2 application bigIp urls. For eg: http://abc.com and http://xyz.com.However on hitting either of the url ,the request is redirected and routed from another bigIp url,eg: http://sssh.com.Now i want to configure this app in OL using java saml.How do we configure multiple entity in same connector as we can use only 1 connector.

**Comment by pitbulk** [comment]
Why you can only use 1 connector?

Each app, http://abc.co,  http://xyz.com.However  and  http://sssh.com.Now   is a Service Provider, so you may configure one Onelogin connector per SP.

**Comment by pitbulk** [comment]
If all is under a load balancer, you may set at OL the public url of the balancer, and in each app, enable with java-saml the Service Provider, but be sure you configure it not with the local urls, but with the load balancer url.

**Comment by abhi68** [comment]
Hey @pitbulk ,thanks for your response.Having separate  connector for the  urls is not possible as the application  is built on same package.So, I think it won't be possible to have multiple  onelogin.saml.properties for configuring different  urls and keep under same package
