### ISSUE TITLE
SLO : Returning Failure LogoutResponse from SP

### ISSUE THREAD

**Issue by ProcrastinatorCp** [onelogin/java-saml#242]
Is it possible to provide a way in **LogoutResponse.build()** to set status as anything other than **Success** ?   

- The current `getLogoutResponseTemplate()` always have the **status** as *status:Success* .

**Comment by pitbulk** [comment]
See https://github.com/onelogin/java-saml/commit/e43459b5fb7220224c36f48cff4e1cb31603336c
