### ISSUE TITLE
SAMLResponse, present in Form Data with no Request Parameter -- causes HTTP-POST error

### ISSUE THREAD

**Issue by swdgit** [onelogin/java-saml#246]
Ok, so I'm able to unpack the SAMLResponse using response.getInputStream() and get all the data I need for Auth... (note, my issue is at work and I don't have access to specifics until tomorrow.)

I'm guessing that this may be something in the configs I'm not doing "just right" and or the MickySoft ADFS configs need a special button pushed... Either way. If anyone has some insight I'd appreciate it. 

Does anyone know of a condition where the SAMLResponse is in the Form Data and not accessible as a  requestParameter?

**Comment by sunkaiqin** [comment]
Are you using a JAX-RS REST framework like Jersey in front of OneLogin SAML Java library?

**Comment by swdgit** [comment]
Yes and it's an @POST. Are you thinking the @Consumes section should be something specific? 

The same issue was also present when another dev was just using the samples directly. i.e. the acs.jsp was giving us the same response. Which is why I was leaning to a dorked up config on either our end with onelogin.properites and or how MS ADFS is configured.

**Comment by sunkaiqin** [comment]
Here is the code for ACS endpoint of REST API:
![image](https://user-images.githubusercontent.com/24231989/68629611-71e8e680-04b2-11ea-8bc7-658242b9bbf3.png)

In a Servlet filter (this filter should be defined before hitting Jersey ) could be coded like this:
![image](https://user-images.githubusercontent.com/24231989/68629720-d310ba00-04b2-11ea-814f-9c0958a1ebdb.png)

**Comment by sunkaiqin** [comment]
Here is the link may be interesting to you regarding this issue: https://download.oracle.com/javaee-archive/jersey.java.net/users/2010/01/9275.html

**Comment by swdgit** [comment]
sounds good. I'll give these a shot tomorrow in the am.
