### ISSUE TITLE
Invalid date format in authentication request

### ISSUE THREAD

**Issue by dhatanian** [onelogin/java-saml#25]
The current date format in `AuthRequest` is `yyyy-MM-dd'T'H:mm:ss'Z` but :

 * There is an `H` missing
 * This will not generate the right date for servers that are not on the UTC time

Instead I would use this to configure the date format :

    SimpleDateFormat simpleDf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
    simpleDf.setTimeZone(TimeZone.getTimeZone("GMT"));

**Comment by pitbulk** [comment]
Solved: https://github.com/onelogin/java-saml/pull/38
