### ISSUE TITLE
Add a "stay" parameter to Auth processSlo 

### ISSUE THREAD

**Issue by cip123** [onelogin/java-saml#250]
Unlike other actions, `processSlo` doesn't take a `stay` parameter and that would be useful for the following situation.
  The SamlRequest comes, you want to delete a cookie if everything is alright and then redirect to the Identity Provider. But since you don't have a stay parameter, there is no time to delete the cookie once the response is validated because the response is already redirected to the Identity Provider.

If you like this idea, I can come up with a PR

**Comment by pitbulk** [comment]
Hi @cip123,

sorry for the delayed reply.

were you able to implement the stay parameter for processSlo?

I think is something that would be great to have, maintaining the default behavior to execute the redirections.
Do you have a PR?

**Comment by pitbulk** [comment]
Implemented
