### ISSUE TITLE
Make signature validation optional in non-strict mode

### ISSUE THREAD

**Issue by cip123** [onelogin/java-saml#251]
I was trying to do some functional testing for onelogin, and I ran into this issue. I wanted to mock a SamlResponse by copying an existing one and replacing the data but the signature validation fails, like it is supposed to. 

Since signing the SamlResponse would be a little too much for a mock, I was wondering if we could make signature validation optional in strict mode.

**Comment by pitbulk** [comment]
Sorry, we can't make optional the signature validation. It has security implications.
