### ISSUE TITLE
Linking a logout request with a SSO session

### ISSUE THREAD

**Issue by abhi-nanobi** [onelogin/java-saml#254]
Hi, we are in the process of integrating SAML authentication in our application. The authentication information received from the IDP is used to create a session on our application and we store this information as well. On logout (IDP initiated) we need to expire the sessions created in our application. While the login is working well, we are facing some problems in the logout flow. The logout request (initiated by logging out of the OneLogin portal) is missing the sessionIndex. Shouldn't the sessionIndex be a part of this required or are we missing something. In the absence of this what is the other way to link the logout request the session created earlier. Any inputs in this matter will help.

Thank You.

**Comment by pitbulk** [comment]
The SessionIndex is a parameter of the [LogoutRequest constructor](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java#L123).
```
public LogoutRequest(Saml2Settings settings, HttpRequest request, String nameId, String sessionIndex, String nameIdFormat, String nameIdNameQualifier, String nameIdSPNameQualifier) 
```
are you providing the to the [logout](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L467) method the SessionIndex value?
```
public String logout(String returnTo, String nameId, String sessionIndex, Boolean stay, String nameidFormat,
			String nameIdNameQualifier, String nameIdSPNameQualifier)
```
