### ISSUE TITLE
 SamlResponse: - Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd

### ISSUE THREAD

**Issue by 1073876389** [onelogin/java-saml#255]
![image](https://user-images.githubusercontent.com/33409711/76681252-0bc0cb80-662c-11ea-9aaa-88cc55493af7.png)
![image](https://user-images.githubusercontent.com/33409711/76681280-6b1edb80-662c-11ea-9a44-b3f28cdba99f.png)
The problem arises when I parse the SAMLResponse,Can you help me locate the cause of the error

**Comment by pitbulk** [comment]
The error of the java app seems related to the fact that the XML seems not following the schema, first of all, try to validate the XML. You can use one of those tools to see what is wrong:
- https://www.samltool.com/validate_xml.php
- https://www.xmlvalidation.com/

**Comment by 1073876389** [comment]
Thank you for your reply, I checked the XML file through the above website and found that there is no problem. After I checked the specific error code by reporting the cause, I found that the java-saml dependency package xercesImpl.jar and my local environmentThe inconsistent version caused an error. I am using a higher version 2.12. This problem is currently solved. Thank you very much.
