### ISSUE TITLE
Support for multiple IDP certificates doesn't seem to work

### ISSUE THREAD

**Issue by sfodje** [onelogin/java-saml#256]
I have an IDP with multiple x509 certificates.
I've noticed that authentication always fails if `onelogin.saml2.idp.x509cert` isn't the right certificate, even if the right certificate is included in `onelogin.saml2.idp.x509certMulti`.
From what I understand from the code, `validateSign` should be called for all given certificates until it returns true, so I'm not sure why this is happening.

**Comment by sfodje** [comment]
Sorry, looks like I was using it wrong.
Closing.

**Comment by ddarling85** [comment]
Hi @sfodje.  Can you tell me how you are configuring the onelogin.saml2.idp.x509certMulti parameter in your onelogin.saml.properties file.  We have not done this before and could use some input in how to get it working.  Thanks.

**Comment by sfodje** [comment]
The problem I had before was with how I set the multiple certificates. 
Originally, I set it using the hash map property:
```java
Map<String, Object> samlData = new HashMap<>();
samlData.put(SettingsBuilder.STRICT_PROPERTY_KEY, Boolean.TRUE.toString());
...
List<X509Certificate> certificates = ...;
samlData.put(SettingsBuilder.IDP_X509CERT_PROPERTY_KEY, CollectionUtils.firstElement(certificates));
samlData.put(SettingsBuilder.IDP_X509CERTMULTI_PROPERTY_KEY, certificates);
...
SettingsBuilder builder = new SettingsBuilder();
Saml2Settings saml2Settings = builder.fromValues(samlData).build();
```

Unfortunately, I found out that it expects the `onelogin.saml2.idp.x509certMulti` to be a list of strings and not a list of `X509Certificate` objects. The workaround was to set the multi certs via the Saml2Settings `setIdpx509certMulti` method:
```java
Map<String, Object> samlData = new HashMap<>();
samlData.put(SettingsBuilder.STRICT_PROPERTY_KEY, Boolean.TRUE.toString());
...
List<X509Certificate> certificates = ...;
samlData.put(SettingsBuilder.IDP_X509CERT_PROPERTY_KEY, CollectionUtils.firstElement(certificates));
...
SettingsBuilder builder = new SettingsBuilder();
Saml2Settings saml2Settings = builder.fromValues(samlData).build();
saml2Settings.setIdpx509certMulti(certificates);
```

Hope that helps.
