### ISSUE TITLE
Why is Saml2Settings#getSPcert() required?

### ISSUE THREAD

**Issue by joaonuno** [onelogin/java-saml#259]
I noticed that I can provide a different SP cert to this library than the one I register at the IdP and it still works (as long as the private key matches the cert registered with the IdP).

There's one validation that **requires** me to provide the SP cert in `Sal2Settings#checkSPCerts()` `return (cert != null && key != null)` but I couldn't find why the SP cert is needed except for exposing it in the SP metadata.

I think that signing login/logout requests only uses the SP key. Am I misunderstanding something?

**Comment by pitbulk** [comment]
The SP public cert is used to publish it on the SP metadata, so the IdP can read it from the SP Metadata URL. No other reason for requiring it.

So basically when the Signature is involved, both cert and private key are requested, but really only uses the private key. You will find that practice in several implementations.

**Comment by joaonuno** [comment]
Thank you for your answer, confirmed my understanding.
