### ISSUE TITLE
onelogin demo client with keycloak

### ISSUE THREAD

**Issue by devmanspi** [onelogin/java-saml#260]
I'm trying to set up the onelogin demo app as SP with a keycloak server as IdP. It's working so far that I'm getting redirected to my keycloak login page. The login works and keycloak creats a session but in the demo app it says "Not authenticated" and "invalid_response". Anyone here tried this with keycloak or can tell me why the app can't handle the response from keycloak?

**Comment by pitbulk** [comment]
When the debug is enabled on the settings of java-saml, the [reason for the SAMLResponse to be invalidated is prompted](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/webapp/acs.jsp#L43).

Enable the [debug at the settings](https://github.com/onelogin/java-saml/blob/master/samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties#L7)

**Comment by devmanspi** [comment]
Thank you. That helped me. I fixed my problem now!
