### ISSUE TITLE
external properties file

### ISSUE THREAD

**Issue by devmanspi** [onelogin/java-saml#262]
Is there a way to read the properties from an external path? I can only use a different file name but no other path than the classpath.

**Comment by pitbulk** [comment]
Any reason for not adding the external path to your classpath?

**Comment by pitbulk** [comment]
You can always edit the [fromFile](https://github.com/onelogin/java-saml/blob/58fc7925a2e1e3d222c811239ed483b8f8a042ae/core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java#L146) method to accept a full path file or add a new method fromCustomPathFile to read from your desired path

**Comment by devmanspi** [comment]
Yeah that's what I did now. I was using the maven dependency so I was not able to change the method there. Now I compiled this dependency on my own with the changed fromFile method.
Thanks for your help.

**Comment by pitbulk** [comment]
@devmanspi 
If you want to contribute it, send a PR and maybe I can add this to the core project.
