### ISSUE TITLE
Support for timestamps in yyyy-MM-dd'T'HH:mm:ss.ffff'Z' format

### ISSUE THREAD

**Issue by erictoom** [onelogin/java-saml#263]
We have an integration that sends timestamps in the yyyy-MM-dd'T'HH:mm:ss.ffff'Z' format.  An example of this format is 2013-12-10T04:39:31.1205Z.  This is failing due to the current Util.parseDateTime implementation that uses the following static formats:

- yyyy-MM-dd'T'HH:mm:ss'Z'
- yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

Would it be possible to update this to support the ffff pattern by using something like ISODateTimeFormat.dateTime().withChronology(ISOChronology.getInstanceUTC()) that will support both the .SSS and the .ffff formats?

**Comment by pitbulk** [comment]
I believe the yyyy-MM-dd'T'HH:mm:ss.SSS'Z' format [is supported](https://github.com/onelogin/java-saml/blob/fd80067b0d77cf6a8fb8fabe24df2fccf6cb10e3/core/src/main/java/com/onelogin/saml2/util/Util.java#L108)

**Comment by erictoom** [comment]
Sorry for the delay.  The issue is that in one of our integrations the timestamps are coming across in the yyyy-MM-dd'T'HH:mm:ss.ffff'Z' format, an example being 2020-05-01T05:56:21.3324Z.

This is failing in the Util.parseDateTime method with an exception that 4Z was unexpected because it only allows 0 or 3 decimal places.

**Comment by pitbulk** [comment]
What version of java-saml are you using?
The latest version of [parseDateTime](https://github.com/onelogin/java-saml/blob/fd80067b0d77cf6a8fb8fabe24df2fccf6cb10e3/core/src/main/java/com/onelogin/saml2/util/Util.java#L1733) as you can see:
```
public static DateTime parseDateTime(String dateTime) {
		DateTime parsedData = null;
		try {
			parsedData = DATE_TIME_FORMAT.parseDateTime(dateTime);
		} catch(Exception e) {
			return DATE_TIME_FORMAT_MILLS.parseDateTime(dateTime);
		}
		return parsedData;
}

DATE_TIME_FORMAT = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss'Z'").withZone(DateTimeZone.UTC);
DATE_TIME_FORMAT_MILLS = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").withZone(DateTimeZone.UTC);
	
```
handles yyyy-MM-dd'T'HH:mm:ss.ffff'Z' format

**Comment by erictoom** [comment]
I was using 2.5.0.  Locally hitting against master I was able to still encounter the problem.  I updated the UtilsTest.testParseDateTime method to the following.

        public void testParseDateTime() {
		long time = 1386650371L;
		String datetime = "2013-12-10T04:39:31Z";
		DateTime parsedTime = Util.parseDateTime(datetime);
		assertEquals(time, parsedTime.getMillis() / 1000);
		
		// Now test if toolkit supports miliseconds
		String datetime2 = "2013-12-10T04:39:31.120Z";
		DateTime parsedTime2 = Util.parseDateTime(datetime2);
		assertEquals(time, parsedTime2.getMillis() / 1000);

		// Now test if toolkit supports fractional seconds
		String datetime3 = "2013-12-10T04:39:31.1205Z";
		DateTime parsedTime3 = Util.parseDateTime(datetime3);
		assertEquals(time, parsedTime3.getMillis() / 1000);
	}

And that test failed with the following exception: 

     java.lang.IllegalArgumentException: Invalid format: "2013-12-10T04:39:31.1205Z" is malformed at "5Z"

	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)

**Comment by pitbulk** [comment]
Can you add:
```
import org.joda.time.format.ISODateTimeFormat;
```
to the Utils file and then replace

the parseDateTime method by:
```
public static DateTime parseDateTime(String dateTime) {
    DateTimeFormatter formatNoMillis = ISODateTimeFormat.dateTimeNoMillis().withZoneUTC();
    DateTimeFormatter formatWithMillis = ISODateTimeFormat.dateTime().withZoneUTC();

    DateTime parsedData = null;
    try {
        parsedData = formatNoMillis.parseDateTime(dateTime);
    } catch(Exception e) {
        return formatWithMillis.parseDateTime(dateTime);
    }
    return parsedData;
}

**Comment by erictoom** [comment]
Yes, with that change the tests were successful.

**Comment by pitbulk** [comment]
ok, I will fix this in a future release.

**Comment by erictoom** [comment]
Thank you!  Looking forward to the new release.

**Comment by amasson88** [comment]
I have a similar error with a third-party SSO:
`Invalid format: "2020-07-10T14:18:09.5206972Z" is malformed at "6972Z"`
