### ISSUE TITLE
Documentation for Integrating with OneLogin SAML Test

### ISSUE THREAD

**Issue by ecerami** [onelogin/java-saml#27]
Thanks for making java-saml available.

I'd like to learn how to use this library by connecting to the OneLogin SAML Test App.

Is there documentation on how to configure the basic web app in the java-saml repo with specifics for the OneLogin SAML Test App?

Thanks for any help on this.

**Comment by pitbulk** [comment]
Here is some:
* https://developers.onelogin.com/saml/java
* https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector
