### ISSUE TITLE
NullPointerException when onelogin.saml2.sp.assertion_consumer_service.url is empty

### ISSUE THREAD

**Issue by Tingil79** [onelogin/java-saml#271]
Affects version 2.5.0

Steps to reproduce:
1. Prepare an otherwise valid properties file with empty onelogin.saml2.sp.assertion_consumer_service.url
1. Load the file into an object of type java.util.Properties
1. Create a Saml2Settings object from it (e.g. via new SettingsBuilder().fromProperties(properties).build())
1. Call getSPMetadata() on your Saml2Settings object, which will give you an NPE.

The cause seems to be in line 150 in com.onelogin.saml2.settings.Metadata where toString() is called on a null URL object.

**Comment by pitbulk** [comment]
You may set a value. assertion_consumer_service URL is a required parameter.
