### ISSUE TITLE
Invalid response due to http vs https

### ISSUE THREAD

**Issue by fatmcgav** [onelogin/java-saml#274]
Hi there,

I'm trying to debug an issue we're having deploying TeamCity using SAML login using the `SAML` [plugin](https://github.com/morincer/teamcity-plugin-saml), which is using the OneLogin SAML toolkit under the hood.

The error I'm getting in the application is:
```
[2020-08-14 19:01:04,007]  ERROR - login.saml2.authn.SamlResponse - The response was received at http://ci.***.co/app/saml/callback instead of https://ci.***.co/app/saml/callback
```

In our setup, TeamCity server is deployed on GKE using Nginx-ingress, sat behind a L3 GCP Load balancer. 
Looking at the Nginx config, it aligns with that defined in the TeamCity [docs](https://www.jetbrains.com/help/teamcity/how-to.html#NGINX).
I've also configured Tomcat to use the "RemoteIPValue" [approach](https://www.jetbrains.com/help/teamcity/how-to.html#Proxy-Tomcat-RemoteIpValve).

I did notice a potential issue on the AuthN request where the `RelayState` field is being set to the `http` rather than the `https` URL, but even setting the value to `https`, I still get the same error.
So I think that's a symptom rather than a cause.

TeamCity is running within Tomcat, and I've gone and enabled access logging, plus the values of the `X-Forwarded-*` and `X-Scheme` headers, and they all look to be as I'd expect:
```
10.60.0.5 - - [17/Aug/2020:14:26:02 +0000] "POST /app/saml/callback HTTP/1.1" 302 - 94.173.235.94 ci.***.co https https
```

The relevant call to `auth.login()` is here: https://github.com/morincer/teamcity-plugin-saml/blob/9e98fee9953a52940438f961f7451c41cc785e5b/saml-authentication-server/src/main/java/jetbrains/buildServer/auth/saml/plugin/SamlAuthenticationScheme.java#L88

I did manage to get a successful login flow by disabling `Strict` mode, but I understand that's not advised for Production environments.

Any suggestions or pointers on how to investigate further?

**Comment by morincer** [comment]
So, first things first. 
Are you able to provide the dump of the SAML request which TC receives? I need to check the request URL. And what URL is configured for the TC server (on the Settings - General page)?
Internally, SAML authentication takes request's URL and compares it with configured callback URL. The plugin takes the base from TC configuration.

**Comment by pitbulk** [comment]
If you are under a proxy or load balancer, read this:
https://github.com/onelogin/java-saml#working-behind-load-balancer

**Comment by fatmcgav** [comment]
Sorry, forgot to update this ticket.

Yes, configuring the Tomcat connector got things working.
I'm wondering why it's required though, as Tomcat was configured with the RemoteIPValue filter, which provided the correct logging etc.

Is this due to this library implementing it's own HTTPRequest class which doesn't have the logic to lookup the `X-Forwarded-*` headers?

**Comment by pitbulk** [comment]
With the use of the [RemoteIPValue filter](https://tomcat.apache.org/tomcat-8.5-doc/config/filter.html#Basic_configuration_to_handle_'x-forwarded-for'), 

request.scheme should retrurn **https** instead **http**

The currentUrl is calculated [at](https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L104)
```
currentUrl = request.getRequestURL();
```

so should be an issue with the getRequestURL method.

**Comment by fatmcgav** [comment]
@pitbulk so to confirm, it's a Tomcat issue?

**Comment by fatmcgav** [comment]
@pitbulk The reason I asked the previous is that it looks like the `HTTPRequest` class is over-loaded within the `java-saml` project - https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/http/HttpRequest.java

So is it possible the `HTTPRequest` implementation here is missing some functionality?

**Comment by pitbulk** [comment]
How are you initializing the Auth object? Are you providing an HttpServletRequest request object with this [method](https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L236) or a similar constructor?

**Comment by fatmcgav** [comment]
So the Auth request is being initialized here: https://github.com/morincer/teamcity-plugin-saml/blob/9e98fee9953a52940438f961f7451c41cc785e5b/saml-authentication-server/src/main/java/jetbrains/buildServer/auth/saml/plugin/SamlAuthenticationScheme.java#L85-L89 using this method: https://github.com/onelogin/java-saml/blob/4444fa03e63c363b15f4faece02ea41a2d910693/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L284

**Comment by pitbulk** [comment]
So your request object is in fact a javax.servlet.http.HttpServletRequest object
```
    public void sendAuthnRequest(@NotNull HttpServletRequest request, @NotNull HttpServletResponse response) throws IOException, SettingsException {
        var samlSettings = buildSettings();
        var auth = new Auth(samlSettings, request, response);
        auth.login();
    }
```

can you add some debug at the beginning of the method and check what value is returned when you call
```
request.getRequestURL()
```
If that returns **http** instead **https** will indicate that the issue is with the original request and nothing related to java-saml.
