### ISSUE TITLE
a new release?

### ISSUE THREAD

**Issue by chenrui333** [onelogin/java-saml#277]
👋  Thanks for creating this utility library, it is really helpful. 

I saw the last release happened almost a year back, do you want to push a new release? Or in general maybe setup some cadence of pushing the new releases?

Appreciate it!!

cc @pitbulk

**Comment by pitbulk** [comment]
Yes, I have in mind to release a new version soon.

**Comment by chenrui333** [comment]
My pleasure, thanks for maintaining this lib and make our lives better. 😄

**Comment by chenrui333** [comment]
Thanks @pitbulk!!

**Comment by pitbulk** [comment]
Version 2.6.0 released:
- https://github.com/onelogin/java-saml/releases/tag/v2.6.0

Soon will be available at Maven Central as well.
