### ISSUE TITLE
Expose a constructor for `com.onelogin.saml2.authn.SamlResponse` which doesn't require `HttpRequest`

### ISSUE THREAD

**Issue by slipset** [onelogin/java-saml#283]
If we look at the constructor for `com.onelogin.saml2.authn.SamlResponse`, we see

```Java
public SamlResponse(Saml2Settings settings, HttpRequest request) throws XPathExpressionException, ParserConfigurationException, SAXException, IOException, SettingsException, ValidationError {
		this.settings = settings;

		if (request != null) {
			currentUrl = request.getRequestURL();
			loadXmlFromBase64(request.getParameter("SAMLResponse"));
		}
	}
```

If we could add a constructor which was
```Java 
public SamlResponse(Saml2Settings settings, String currentUrl, String samlResponse) throws XPathExpressionException, ParserConfigurationException, SAXException, IOException, SettingsException, ValidationError {
		this.settings = settings;
		this.currentUrl = currentUrl;
		loadXmlFromBase64(samlResponse));
	}
```

Then the original constructor could delegate to this new constructor, and it would be easier to use `SamlResponse` from systems which do not use `HttpRequests`.

The reason I'm asking for this is that I would like to use this library from a Clojure application, where http-requests typically are handled as maps, and it's somewhat contrived to construct a `HttpRequest` just to pull out the url and the samlResponse.

I'd be happy to provide a PR if this is something you would find useful

**Comment by pitbulk** [comment]
Yes, add the method and provide the unit tests.
