### ISSUE TITLE
 No authentication method, requested by the service provider

### ISSUE THREAD

**Issue by ZahidSafi** [onelogin/java-saml#287]
We are having an issue getting the login page response in "java-saml-tookit-jspsample" working. And this issue is in reference to a previous issue that was closed before: "invalid value on onelogin.saml2.security.requested_authncontext #137" and we believe it to be an issue with property as well: 
onelogin.saml2.security.requested_authncontext = urn:oasis:names:tc:SAML:2.0:xc:classes:Password
but we are uncertain to what information we would need. 
our shib is: 
idp_version: 2.3.8
And this in the idp-process log: 10:07:18.514 - WARN [edu.internet2.middleware.shibboleth.idp.authn.AuthenticationEngine:308] - No authentication method, requested by the service provider, is supported

any help on this issue would be greatly appreciated.

**Comment by pitbulk** [comment]
The value on the demo settings is right:
https://github.com/onelogin/java-saml/blob/9588c495663846f83d6cc30d596bf931ee27cd6b/samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties

I see the one on the Readme is wrong.

**Comment by pitbulk** [comment]
You should set:
onelogin.saml2.security.requested_authncontext = urn:oasis:names:tc:SAML:2.0:xc:classes:Password

If that is the AuthNContext supported by your IdP.

Otherwise, set 
onelogin.saml2.security.requested_authncontext = urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified

Or leave it empty

**Comment by ZahidSafi** [comment]
oh okay, thank you! so we did try that and clicking the login button brought up our login page , but puting in our own user information brought gave us this error: 
invalid_response

The status code of the Response was not Success, was urn:oasis:names:tc:SAML:2.0:status:Responder -> Unable to encrypt assertion

and this is with leaving onelogin.saml2.security.requested_authncontext =, to be empty as we have already tried the other idea you suggested. 

so we tried to fill this in the property
onelogin.saml2.sp.privatekey =
and this as well 
onelogin.saml2.sp.x509cert =

and we got the cert and private key by trying to get a self sign cert from here: https://developers.onelogin.com/saml/online-tools/x509-certs/obtain-self-signed-certs

and we still are getting the same issue, what would you think could be missing  for it to have a invalid response?

**Comment by pitbulk** [comment]
Unable to encrypt assertion is an issue in the IdP side who is not able to encrypt the Assertion of the generated SAMLResponse.

Is possible that you configured the IdP to encrypt the Assertion but you have not provided to the IdP the SP public cert to be used on the encryption process.

if you run the demo and you access to the metadata URL, if the onelogin.saml2.sp.privatekey and onelogin.saml2.sp.x509cert  are ok, and the onelogin.saml2.security.want_assertions_encrypted = true,  the SP metadata should contain a KeyDescription for the encryption process. You should register it properly on your IdP

Or if you don't require encrypted assertion on your use case, try disable it on your IdP.
