### ISSUE TITLE
IdPMetadataParser behaves correctly?

### ISSUE THREAD

**Issue by ArjanSchouten** [onelogin/java-saml#289]
Library version: 2.6.0
Java version: 11.0

We want to create saml2 settings from our own configuration and enrich the saml2 settings with data retrieved from the IDP metadata. However, when we use the `IdPMetadataParser.injectIntoSettings` we lost the contact, organization and unique_prefix_id properties.

Code not working as expected:
```
var settings = new SettingsBuilder()
    .fromValues(new HashMap<>(saml2Configuration.getSettings()))
    .build();

Map<String, Object> idpSettings = IdPMetadataParser.parseRemoteXML(new URL(idpMetadataUrl));

IdPMetadataParser.injectIntoSettings(settings, idpSettings)
```

Code that works (for us):
```
Map<String, Object> settings = new HashMap<>(saml2Configuration.getSettings());
Map<String, Object> idpSettings = IdPMetadataParser.parseRemoteXML(new URL(idpMetadataUrl));

settings.putAll(idpSettings);

Saml2Settings saml2Settings = new SettingsBuilder()
    .fromValues(settings)
    .build();
```

Shouldn't the `IdPMetadataParser.injectIntoSettings` method behaviour equal the code above?

**Comment by pitbulk** [comment]
That unit test covered the injectIntoSettings method:
https://github.com/onelogin/java-saml/blob/master/core/src/test/java/com/onelogin/saml2/test/settings/IdPMetadataParserTest.java#L213
And verified that IdP data was updated, but we didn't tested that rest of settings remind.

I gonna make some tests

**Comment by pitbulk** [comment]
@ArjanSchouten,

I identified the issue, see this PR: https://github.com/onelogin/java-saml/pull/296

Added unit test to cover all those settings.

**Comment by ArjanSchouten** [comment]
Thanks for fixing the issue! Looks good!
