### ISSUE TITLE
How can I add login_hint as a parameter in Auth.login method

### ISSUE THREAD

**Issue by hamusi** [onelogin/java-saml#291]
https://github.com/onelogin/java-saml/blob/master/toolkit/src/main/java/com/onelogin/saml2/Auth.java#L332
I don't see a way, how to add custom parameter, is that possible?

**Comment by pitbulk** [comment]
There is no way to add a custom parameter to the method, but not hard to support it at all:

You can call login with stay=true, then you will get an URL string from the login method.
Concat to the string the login_hint=xxx and then execute a redirection to the result URL string.

**Comment by pitbulk** [comment]
Hi @hamusi,

I added an easy way to add extra parameters to the login and login method
A new HashMap parameter that could contain the extra GET parameters you wanted to sent.

See https://github.com/onelogin/java-saml/commit/ec3af78bd6836fc98b27bac79099cb27a817a0f5
