### ISSUE TITLE
SamlResponse getAssertionNotOnOrAfter () returns alaways null

### ISSUE THREAD

**Issue by Holmesus** [onelogin/java-saml#298]
![image](https://user-images.githubusercontent.com/28487699/105837159-3da30c80-6009-11eb-91b7-59bb1344283a.png)
public DateTime getSessionNotOnOrAfter() throws XPathExpressionException {
		String notOnOrAfter = null;
		NodeList entries = this.queryAssertion("/saml:AuthnStatement[@SessionNotOnOrAfter]");
		if (entries.getLength() > 0) {
			notOnOrAfter = entries.item(0).getAttributes().getNamedItem("SessionNotOnOrAfter").getNodeValue();
			return Util.parseDateTime(notOnOrAfter);
		}
		return null;
	}
the result of this method is alaways null

**Comment by pitbulk** [comment]
I don't see a "SessionNotOnOrAfter" attribute in your SAMLResponse, so you get a null.

Here is the test that verifies that the getSessionNotOnOrAfter method works:
https://github.com/onelogin/java-saml/blob/3515c6498fc04fb200af7955f2692bfbc8d8b9d8/core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java#L1190

**Comment by Holmesus** [comment]
thanks a lot. I'm using Azure AD SSO,it uses <"Conditions
NotBefore="2013-03-18T21:32:51.261Z"
NotOnOrAfter="2013-03-18T22:32:51.261Z"
>" to represent the session expiration.Is that means  "SessionNotOnOrAfter" is not  a standard filed which must appears in the samlresponse？

**Comment by pitbulk** [comment]
not before and NotOnOrAfter are attributes that defines validation of the SAMLResponse itself, they are related to the Session.

SessionNotOnOrAfter is a standard field in SAML 2.0 but it is optional.
