### ISSUE TITLE
Add support for more complex response statuses in LogoutResponse

### ISSUE THREAD

**Issue by mauromol** [onelogin/java-saml#342]
`LogoutResponse` currently supports the specification of just a top-level status code: no second level status code, no status message.
If the consumer needs to produce a partial logout `LogoutResponse` they would need to produce a response with a `urn:oasis:names:tc:SAML:2.0:status:Responder` top-level status code and a `urn:oasis:names:tc:SAML:2.0:status:PartialLogout` second-level status code.
This enhancement request is to add the ability to specify a `SamlResponseStatus` in `LogoutResponse.build(...)` to properly set a more complex response status (a top-level status code, optionally a second-level status code and optionally a status message).

I don't have a PR ready for this because it's based on previous work (like #315) but here is a preview: https://github.com/mauromol/java-saml/commit/d8695c946b579b361dc906f7355b412a561600e9.

**Comment by pitbulk** [comment]
@mauromol now you can provide this PR
