### ISSUE TITLE
Azure AD rejects the SAML Request indicating "Subject" is not supported

### ISSUE THREAD

**Issue by jadsafe** [onelogin/java-saml#357]
We've been successfully (and happily) using OneLogin's Java-SAML library for our SaaS application and it's been working well with OneLogin and Okta identity providers. We just started using it against Azure AD and we are running into a problem specifically with the SP-initiated login.

Microsoft Azure AD is failing the SAML request with the error:
"AADSTS900236: The SAML authentication request property 'Subject' is not supported and must not be set."

The use of "<saml:Subject>" is coming from the Java SAML library, wondering if you have insights on why it may not be accepted by Azure AD.

This is a sample request being made to Azure AD with a few tokens/email-addresses replaced with HIDDEN.

<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_hidden" Version="2.0" IssueInstant="2021-08-17T19:14:01Z" Destination="https://login.microsoftonline.com/HIDDEN/saml2" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://launch.terratrue.com/idp-sso-login/HIDDEN">
  <saml:Issuer>https://launch.terratrue.com/sso</saml:Issuer>
  <saml:Subject>
    <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">hidden@gmail.com
    </saml:NameID>
    <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
    </saml:SubjectConfirmation>
 </saml:Subject>
 <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" AllowCreate="true" />
</samlp:AuthnRequest>

**Comment by jadsafe** [comment]
To follow-up on my own issue, it appears that we can pass a null or empty nameIdValueReq String in the AuthnRequest constructor and the SAML library will no longer create a saml:Subject entity in the SAML request. SP-initiated login with Azure AD will then work, at least in my initial tests just now.

**Comment by mauromol** [comment]
Yes, indeed the nameIdValueReq parameter is meant to request login for a subject for which an identification name is known in advance. If the authentication system does not want any subject name to be proposed, or if this is unknown, than simply omitting it will cause the SAML authentication system to determine it by virtue of the authentication process on IdP side. It depends on the scenario and whether (and how) account linking is involved or not.
