### ISSUE TITLE
Response audiences are validated against currentUrl

### ISSUE THREAD

**Issue by npouvesle** [onelogin/java-saml#37]
https://github.com/onelogin/java-saml/blob/master/src/main/java/com/onelogin/saml/Response.java#L153
<code>
			if (!validAudiences.isEmpty() && !this.audienceUrl.equals(currentUrl)) {
				throw new Exception( this.audienceUrl + " is not a valid audience for this Response");	
			}
</code>

If I understand the code correctly audiences should not be validated against currentUrl but against the SP entity ID (the python lib does that).

I changed the code to:

<code>
			if (!validAudiences.isEmpty() && !this.audienceUrl.equals(this.accountSettings.getIdp_sso_target_url())) {
				throw new Exception( this.audienceUrl + " is not a valid audience for this Response");	
			}
</code>

but that might be wrong since I'm not entirely familiar with that validation.

**Comment by smchristensen** [comment]
I've also noticed that if the audience is left blank on the server-side configuration that the response comes back with the string "{audience}" in the <AudienceRestriction> node.  Likewise if the recipient is left blank on the server side configuration, the Destination attribute in the root SAML node is set to "{recipient}".  I think there are bugs in the SAML implementation.

**Comment by pitbulk** [comment]
This is solved in [2.0.0 version](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L219)

The {audience} // {recipient} issue was an issue on the Onelogin App Test connector.
I recommend to always fill the fields
