### ISSUE TITLE
Is 2.9.0 an official release?

### ISSUE THREAD

**Issue by act-amirsky** [onelogin/java-saml#385]
Tags has 2.9.0 as latest (and we see it in maven-repository)
However the releases tab declares 2.8.0 as latest.

Is 2.9.0 the current official release or 2.8.0?

**Comment by mauromol** [comment]
That's an interesting question, I didn't even know about 2.9.0. Any feedback from the maintainers (@bzvestey)? I'm also waiting for feedback on #307 and #368, which I really hoped could be included in 2.9.0 :-(

**Comment by act-amirsky** [comment]
I see things have not changed. @bzvestey , can you please shed some light on this? Is 2.9.0 an "official" release yet?

**Comment by bzvestey** [comment]
Release made for 2.9.0, it looks like it was just never added to the releases page after the build was pushed to maven repo we use.
