### ISSUE TITLE
Please publish to Maven Central

### ISSUE THREAD

**Issue by Randgalt** [onelogin/java-saml#39]
Issue #12 is closed - don't know why. The JARs are NOT on Maven Central.

**Comment by chr1st1anh** [comment]
+1

**Comment by pitbulk** [comment]
Threre is no official release, we are still getting feedback of the candidate 2.0.0 version.

@Randgalt , @chr1st1anh have you tested it?

**Comment by nakaeeee** [comment]
+1

**Comment by ozawa-hi** [comment]
Can you get release 1.1.2 on Maven Central?

**Comment by Anu2g** [comment]
+1

**Comment by Anu2g** [comment]
Looks like they're referencing it as a maven dependency here: https://github.com/onelogin/java-saml/blob/master/sample/pom.xml

`<dependency>
      <groupId>com.onelogin</groupId>
      <artifactId>java-saml</artifactId>
      <version>1.1.2</version>
    </dependency>`

**Comment by steaks** [comment]
+1

**Comment by pitbulk** [comment]
Version 1.1.2 is not secure (it lacks a lot of required SAML 2.0 validations) that why we plan to release only the 2.0.0 version.

Follow: https://github.com/onelogin/java-saml/issues/50
