### ISSUE TITLE
500 error 

### ISSUE THREAD

**Issue by dashinjoy** [onelogin/java-saml#41]
I have configured the toolkit (deployed on Tomcat) to consume a SAML assertion generated by the CA SiteMInder tool. However, the issue is that though the see on the catalina.log that the SAML is being parsed & displayed in the user readable format with the user details, it errors out in the browser with servlet exceptions on consume.jsp.

Please help
-

**Comment by pitbulk** [comment]
Can you detail what version are you using and the servlet exceptions?

**Comment by dashinjoy** [comment]
I think i just resolved it. Thanks anyways.

Regards,
Joydeep Dasgupta

**Comment by matthiasfeurer** [comment]
I know this has been some while ago, but I am facing the exact same issue now.
dashinjoy: could you please reveal how you finally solved this?

Thanks
Matthias
