### ISSUE TITLE
NameIdFormat is hardcoded in AuthRequest.java

### ISSUE THREAD

**Issue by chr1st1anh** [onelogin/java-saml#42]
The NameIdFormat is hardocded currently on line 66 in AuthRequest.java: 
	`writer.writeAttribute("Format", "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified");`
If one wants to change it, its necessary to inherit this class and overwrite the method.

**Comment by pitbulk** [comment]
Use the 2.0.0 version where the Format of the samlp:NameIDPolicy [depends on the settings](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java#L114)
