### ISSUE TITLE
Forming URL for ACS with existing query parameter fails 

### ISSUE THREAD

**Issue by leocrawford** [onelogin/java-saml#46]
The ACS for google is of the form:

https://accounts.google.com/o/saml2/idp?idpid=<hex string>

In AuthRequest.getSSOurl you use string concatenation to form the URL using the "?" seperator. This fails in all URLs that already have a query parameter.

I have made a local fix which simply checks whether the query string already contains "?" and if it does uses "&" instead. Happy to create a pull request, but wondered if you'd prefer to use something like apache URIBuilder (see below) to avoid other possible edge cases, as the cost of an extra dependency?

http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/utils/URIBuilder.html

**Comment by pitbulk** [comment]
Hi @leocrawford,

you should be using the [2.0.0](https://github.com/onelogin/java-saml/tree/v2.0.0) version instead the master branch.

**Comment by leocrawford** [comment]
Wow. You guys have been busy! Much tighter code.
