### ISSUE TITLE
2.0 branch status

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#47]
Hi,

What's the status of the 2.0 branch? It seems that many issues are fixed on that branch, yet still there seems to be no official release, and the README there says not to use it in production.

An update about the status would be appreciated.
Thanks!

**Comment by pitbulk** [comment]
I'm still adding unit test to the library, and need to improve the way the Signatures are validated.
Right now is vulnerable to some "Signature Wrapping attacks".

**Comment by pitbulk** [comment]
Review: https://github.com/onelogin/java-saml/issues/50
