### ISSUE TITLE
Documentation (v2.0.0)

### ISSUE THREAD

**Issue by pitbulk** [onelogin/java-saml#49]
We need to add documentation to the project before release it at Maven.

There are already documentation that already exists at the [PHP](https://github.com/onelogin/php-saml) or [Python](https://github.com/onelogin/python-saml) toolkits.that we can follow as guide.

We need to describe the project scheme, how the settings works, the methods of the main auth class and describe the examples.

In the future we can add examples of how integrate this toolkit on the different Java frameworks.

**Comment by miszobi** [comment]
@pitbulk do you think you'll be able to work on this in the near future? Or would you want somebody else to try creating some docs?

**Comment by pitbulk** [comment]
I plan to start that documentation next week.

**Comment by jasmdk** [comment]
What is the status on this? Is documentation the only thing missing and if so do you still need help?
With regard to integration using Maven the only thing is to write the dependency snippet to include in your maven project - I can provide that for you if you would like that?

**Comment by pitbulk** [comment]
Any help is welcome. The example project I think already has the maven dependency snippet.

I was busy with issues on the rest of the toolkits but now I will be able to push java-saml again.

**Comment by pitbulk** [comment]
@miszobi , @jasmdk, @ThePetrov, @metal-hed

now we have some documentation, please review it and provide any extra info that you consider that we should add.

My plan is to execute the official release next week so please if you have some spare time, give some love to the documentation ;)

**Comment by miszobi** [comment]
Nice. Left some comments on the commit, but looks good to me in general.

**Comment by ThePetrov** [comment]
Looks good in general, added some questions/fixes on the commit

**Comment by metal-hed** [comment]
Looks good to me as well, looking forward to the release!

**Comment by pitbulk** [comment]
Now master is the v2.0.0 branch, I made the suggested changes, if there is no other comment, I plan to release it asap (need to learn first how Sonatype OSSRH works, but I think we are almost ready to publish there).

Related to documentation generated by docstring, correct me but I think that Sonatype can take care of it, right?

**Comment by miszobi** [comment]
Yes, generating the javadoc and source jars should already be handled by the release profile I've set up, then all of those should be uploaded as a part of the release process. 

The instruction [here](https://github.com/onelogin/java-saml/pull/59#issue-171392151) should outline the most important steps. Remember to set up gpg upfront to sign the artifacts.

Let me know if you run into issues, I'll try to help.

**Comment by pitbulk** [comment]
I released 2.0.0 using the mvn command, but I got an error after update due javadocs.
```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project java-saml-core: MavenReportException: Error while creating archive:
[INFO] [ERROR] Exit code: 1 - /home/pitbulk/proyectos/java-saml-onelogin/target/checkout/core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java:101: warning: no description for @throws
[INFO] [ERROR] * @throws IOException
```
I used on my local:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>2.9.1</version>
    <configuration>
        <additionalparam>-Xdoclint:none</additionalparam>
    </configuration>
    <executions>
        <execution>
            <id>attach-javadocs</id>
            <goals>
                <goal>jar</goal>
            </goals>
         </execution>
    </executions>
</plugin>
```
and worked for execute the release... but failing when updaing to sonatype.

Any help?

**Comment by miszobi** [comment]
What's the error you're getting from Sonatype? Did you set up your account credentials in `$HOME/.m2/settings.xml`?

**Comment by pitbulk** [comment]
I think I experienced the error I mentioned
```
Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5:perform (default-cli) on project java-saml-toolkit: Maven execution failed, exit code: '1'
```
at the end of the process since the github release was created, and you can see that the code was updated at sonatype:
https://oss.sonatype.org/content/repositories/snapshots/com/onelogin/java-saml-toolkit/

but nothing at stagging

![image](https://cloud.githubusercontent.com/assets/600897/20592232/9b051a74-b22c-11e6-89ce-be9d3c425dd1.png)

**Comment by miszobi** [comment]
This is the snapshot version, while I'd expect a '2.0.0' (non-snapshot) to be produced as a part of the release. Could you attach the full output from the maven release process?

Maybe try setting up a gitter chat for the project, or just dm me on twitter (@miszobi), so we can chat without bouncing comments here?

**Comment by pitbulk** [comment]
Added you, I'm @lacarab

**Comment by pitbulk** [comment]
Thanks all for the collaboration!
