### ISSUE TITLE
Improvement: Support KeyStore file

### ISSUE THREAD

**Issue by pitbulk** [onelogin/java-saml#55]
In Java environments is common to use a KeyStore file in order to manage the public and private keys.
Let's add support for this.

Related to #54

**Comment by ProcrastinatorCp** [comment]
Hi, I would like to contribute to this feature. 

Can I clarify, where to read the KeyStore file from ?   
Is it to be passed while constructing **Auth** instance ? Something like below :     
```
public Auth(String filename, KeyStore keyStore) {
```

**Comment by pitbulk** [comment]
Yes I think so, and then extend the SettingsBulder to support a method able to extract the public and private keys.

An alternative is to add a new setting field that will refer to the keystore_filename, by default null, but if defined, the SettingsBulder will take care of it.

**Comment by ProcrastinatorCp** [comment]
Could you please review https://github.com/onelogin/java-saml/pull/241
