### ISSUE TITLE
Allow configuring Saml2Settings programatically

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#57]
In 2.0 Saml2Settings can only be fully customized using a properties file (because some of the setXXX() methods are `protected`). 

Sometimes it's useful to be able to customize these programatically (this was possible in 1.0).

**Comment by pitbulk** [comment]
This follows how php-saml and python-saml works, where you can load "setting data" and later change only some properties.

I want to avoid people to use the toolkit in a bad way, that why I want to keep the control of what can be changed.

but notice I made the methods protected in case a project require the customization that you comment and requires to change those values programatically.

**Comment by miszobi** [comment]
Fair enough, though the `SettingsBuilder` object doesn't really seem to do any extra validation (seems the intent for that is there, but the implementation isn't).

I'm thinking about making the `Saml2Settings` constructor protected (and documenting to use `SettingsBuilder` instead), and adding a `Saml2Settings`  (and maybe `Auth`) methods to configure using a `java.util.Properties`object, to allow configuring programatically without subclassing (which would work, but is a bit fragile). 

This would be somewhat analogous to configuring the python version via a json object, and avoid having to write the config in a file just to read it back. Does that sound reasonable?

**Comment by pitbulk** [comment]
Settings validation is done by Saml2Settings at the [checkSettings](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java#L672) method.

The SettingsBuilder contains a method to read the file that contains the properties ([fromFile](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java#L106)) and others to read and load those properties from the file.

Maybe you can implement an extended version of the SettingsBuilder able to read from something different than a property file.

**Comment by miszobi** [comment]
Let's leave this as is for now. I'm okay with just subclassing `Saml2Settings` to set the configuration. But I do appreciate having the possibility of configuring these easily at runtime.

**Comment by dcepler** [comment]
Any chance of re-considering this? I am currently working on migrating a really old version of the library over to the latest where everything was being done via `setXXX()`.
