### ISSUE TITLE
Allow retrieving the id of generated AuthnRequests

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#60]
Currently the `Auth.login` methods return nothing, not allowing the caller to retrieve the id of the generated AuthnRequest, to be used when validating the response (`com.onelogin.saml2.Auth#processResponse(java.lang.String)`)

**Comment by miszobi** [comment]
@pitbulk I'm planning to implement this by making the `login` and `logout` methods return the generated `AuthnRequest`/`LogoutRequest` object. Does that sound good to you?

**Comment by pitbulk** [comment]
login and logout should return nothing since they execute the redirections. On the other toolkits I added a getID method. We should use the same here.

**Comment by miszobi** [comment]
They could still return a value though, execution continues after calling the method and marking the response as a redirect. 
This seems like a nicer api, than calling a getter afterwards (and we'd have to have two getters, one for login and one for logout). Callers that don't care about the id can just ignore the return value.

Let me know what you think.

**Comment by pitbulk** [comment]
I just try to  maintain the toolkit as similar as possible, to help on the global manibtenance.

**Comment by miszobi** [comment]
Okay. I'll add the extra getId methods.
