### ISSUE TITLE
SAML responses with a InResponseTo attribute not rejected when requestId not passed to validate()

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#62]
When validating a SAML response (using `SamlResponse#isValid(java.lang.String)`), responses that contain a InResponseTo attribute (either as an attribute of  the Response, or the SubjectConfirmationData) are not rejected, even when no requestId was specified as an argument to `isValid`

So a message like
```
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="pfx1ff1da4a-010e-428c-16eb-75f31f16567a" Version="2.0" IssueInstant="2014-02-19T01:37:01Z" Destination="http://localhost:8080/java-saml-jspsample/acs.jsp" InResponseTo="ONELOGIN_5fe9d6e499b2f0913206aab3f7191729049bb807">
...
   <saml:Assertion>
...
      <saml:Subject>
         <saml:NameID SPNameQualifier="http://localhost:8080/java-saml-jspsample/metadata.jsp" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">492882615acf31c8096b627245d76ae53036c090</saml:NameID>
         <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml:SubjectConfirmationData InResponseTo="ONELOGIN_5fe9d6e499b2f0913206aab3f7191729049bb807" />
         </saml:SubjectConfirmation>
      </saml:Subject>
...
   </saml:Assertion>
</samlp:Response>
```

will be accepted by `SamlResponse#isValid(null)`. The [SAML Core spec](https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf) (line 1605), and the [SAML profiles spec](https://www.oasis-open.org/committees/download.php/35389/sstc-saml-profiles-errata-2.0-wd-06-diff.pdf) (line 634) say that if the InResponseAttribute is present it MUST match the value of the corresponding request's ID attribute. Further section 4.1.5 of the SAML profiles spec says that an unsolicited response (i.e. IdP initiated), MUST NOT contain a InResposeTo attribute (line 694), so I believe such messages should be rejected as invalid.

**Comment by pitbulk** [comment]
Is think that is responsibility of the toolkit's user to provide a value for the request_id validation., but I will review that.

**Comment by miszobi** [comment]
Agreed, it's the caller's responsibility to provide a request ID to validate.

The issue here is that when no id is provided (i.e. calling `validate(null)`) both Responses with no InResponseTo attribute and Responses with any InResponseTo attribute accepted. The latter should be rejected, as they are not what the caller is expecting, and not valid according to the SAML spec, as the InResponseTo attribute doesn't match a previously sent AuthnRequest ID.

**Comment by pitbulk** [comment]
On my experience I will say that requestID validation on scenarios where IdP-initiated SSO is a minor issue. More important is to store IDs on the SP to avoid duplicate Message attacks and you will see that no many implementations have that feature.

Im ok invalidating the response if a requestId is not provided to follow strictly what the standard says, but in the real world I think that this will carry more problems to the toolkit users than benefits.
That why I relaxed that check so if a user of the toolkit want to validate the request, simply need to provide it to the validation method.

**Comment by miszobi** [comment]
I understand that when allowing identity-provided initiated SSO the value of checking `InResponseTo` is limited, however both the spec mandates and [OWASP](https://www.owasp.org/index.php/SAML_Security_Cheat_Sheet) advises doing it when applicable. 

With the current behaviour it's not really possible to say "I'm not expecting a response to a previously sent Request, but if this Response is identity-provider initiated I'll allow it" (because calling `validate(null)` will allow both missing `InResponseTo` (which is expected for IdP-initiated) and any `InResponseTo` (which is wrong for IdP-initiated and might be a replay attack). There is no existing ID to provide, because I don't expect any reply in this session.

How about an extra setting in `Saml2Settings` to specify whether the caller wants InResponseTo values rejected when not specified or not?

**Comment by pitbulk** [comment]
Is an extra paramter on the security settings but I think makes sense in this case.
