### ISSUE TITLE
Allow retrieving the processed Assertion ID and NotOnOrAfter value

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#72]
As per [SAML profiles spec](https://www.oasis-open.org/committees/download.php/35389/sstc-saml-profiles-errata-2.0-wd-06-diff.pdf), section 4.1.4.5:

```
The service provider MUST ensure that bearer assertions are not replayed, by maintaining the set of used
ID values for the length of time for which the assertion would be considered valid based on the
NotOnOrAfter attribute in the <SubjectConfirmationData>.
```

To allow the caller to do that, we should allow retrieving the Assertion ID value and the NotOnOrAfter values of the SubjectConfirmationData nodes.

**Comment by pitbulk** [comment]
Makes sense, thanks!
