### ISSUE TITLE
It's possible to add a fake Response signature to a SAML Response, that won't be validated, and will be considered valid with settings.wantMessagesSigned set

### ISSUE THREAD

**Issue by miszobi** [onelogin/java-saml#78]
A SAML Response with the structure:
```
samlp:Response ID='1'
  saml:Assertion ID='2'
    ds:Signature ref='#2'
```
can be modified to have a fake Signature element for the Response:
```
samlp:Response ID='1'
  samlp:Extensions
    saml:Response ID='fake'
      ds:Signature ref='#fake' // not verified, so can have any SignatureValue
  saml:Assertion ID='2'
    ds:Signature ref='#2'
```
Such a message will be considered valid even when `settings.wantMessagesSigned` is set, and the spoofed Response signature will not be verified.

The Assertion is still validated, and needs to be properly signed (messages without both the Response signature and the Assertion signature will be rejected), but potentially this allows the attacker to change some non-Assertion values in the message.

**Comment by pitbulk** [comment]
Hi @miszobi 

the [getWantAssertionsSigned](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L247) and [getWantMessagesSigned](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L251) methods, based on the settings is only a way to let the developer decide if it will be required SAMLResponses with Response signed, Assertion signed or both. The toolkit will consider [invalid any SAMLResponse without signature](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L257).

I thought that the [processSignedElements](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L666) method prevents from the signature wrapping attack that you explained. I think I created enough test on [testIsInValidSign](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java#L1619)
and [testValidateSignedElements](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java#L1680).

I will review your PR carefully

**Comment by miszobi** [comment]
The problem is `processSignedElements` checks which elements are signed, but accepts the elements being in different locations than the (correct) ones checked further on in `validateSign`. So it is possible to pass processSignedElements and further checks with this spoofed Response item, and `validateSign` can be satisfied with only having one of the signatures in place (in this case the Assertion signature).

You can checkout [response_with_spoofed_response_signature.xml](https://github.com/miszobi/java-saml/blob/40eacc65c616b647363d5e6797f870a7e4a30d49/core/src/test/resources/data/responses/invalids/attacks/response_with_spoofed_response_signature.xml) and [AutnResponseTest.java](https://github.com/miszobi/java-saml/blob/40eacc65c616b647363d5e6797f870a7e4a30d49/core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java) to the v2.0.0 branch, and run the test to reproduce.

In the PR, the semantics of `getWantAssertionsSigned` and `getWantMessagesSigned` are preserved, but `processSignedElements` makes sure the signatures are in the expected locations (and that there is only at most one of each), and `validateSign` gets information about which signatures are expected, and rejects messages that don't have the required ones.

**Comment by pitbulk** [comment]
Thanks for contribute on this!
