### ISSUE TITLE
Request: Support IdPs with separate URLs for logout response/request

### ISSUE THREAD

**Issue by metal-hed** [onelogin/java-saml#80]
Hello,

While working with a client to setup SSO with our application I came across this issue. The client is using the solution provided by F5 here https://f5.com/products/modules/access-policy-manager

For SLO, the server has separate URLs for when the SP wants to send a request to logout from the IdP and for when the SP wants to send the IdP a logout response. I modified the library a bit and came up with this to allow this to happen

https://gist.github.com/metal-hed/85932b301233edd5a22d2d5ffd0085b0

Would this be something that could be added into the library?

**Comment by pitbulk** [comment]
Yes, I think we can support that. Can you provide tests as well?

**Comment by metal-hed** [comment]
Hello,

Yes, I can work on that this week and create a pull request when ready.

**Comment by metal-hed** [comment]
I created a PR based off the v2.0.0 branch HEAD. If you'd like to branch from a different starting point let me know and I will make the needed adjustments

**Comment by pitbulk** [comment]
Merged
