### ISSUE TITLE
Allow clock drift when validating NotBefore and NotOnOrAfter attributes

### ISSUE THREAD

**Issue by amanteaux** [onelogin/java-saml#89]
As it is done in the ruby version of the library, https://github.com/onelogin/ruby-saml#clock-drift, would it be possible to configure clock drift?

**Comment by pitbulk** [comment]
Right now is not possible, but this is something that should exists.
are you able to contribute with a PR? 

The idea is to add a new setting to the 'onelogin.saml.properties' with the clock drift value, by default 180 [3min], and use it on time validation.

**Comment by amanteaux** [comment]
Thank you for your response and for validating the idea.

I can do the PR, though it might take me a few weeks to find the time to do it.
