### ISSUE TITLE
Onelogin not returning encrypted response

### ISSUE THREAD

**Issue by openback** [onelogin/java-saml#99]
I've created an integration with Onelogin that works without encryption, but after attempting to turn on encryption, login fails because the response from onelogin is not encrypted. What is the proper way to enable this?

Related settings:
```
# onelogin.saml.properties
###
onelogin.saml2.strict = true
onelogin.saml2.debug = false
onelogin.saml2.security.nameid_encrypted = true
onelogin.saml2.security.authnrequest_signed = true
onelogin.saml2.security.logoutrequest_signed = true
onelogin.saml2.security.logoutresponse_signed = true
onelogin.saml2.security.want_messages_signed = true
onelogin.saml2.security.want_assertions_signed = true
onelogin.saml2.security.sign_metadata = true
onelogin.saml2.security.want_assertions_encrypted = true
onelogin.saml2.security.want_nameid_encrypted = true
urn:oasis:names:tc:SAML:2.0:ac:classes:urn:oasis:names:tc:SAML:2.0:ac:classes:Password
onelogin.saml2.security.requested_authncontext = urn:oasis:names:tc:SAML:2.0:ac:classes:urn:oasis:names:tc:SAML:2.0:ac:classes:Password
onelogin.saml2.security.onelogin.saml2.security.requested_authncontextcomparison = exact
onelogin.saml2.security.want_xml_validation = true
onelogin.saml2.security.signature_algorithm = http://www.w3.org/2000/09/xmldsig#rsa-sha1
###
```

And `onelogin.saml2.sp.entityid` is configured to an endpoint which uses this properties file.

**Comment by pitbulk** [comment]
When you enable
```
onelogin.saml2.security.want_assertions_encrypted = true
```
SAMLResponses with unencrypted Assertions will be rejected.

You may use at Onelogin a connector with the encryption enabled.

If you are using a [SAML-Test-Connector](https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector), you will need to replace it by a SAML Test Connector (IdP) w/encrypt, that will allow you encrypt the assertion.

If you are using a custom app, you will need to contact [Onelogin Help Center](https://support.onelogin.com/hc/en-us/requests/new) open a ticket, provide the ID of your connector and ask them to turn on encryption for that connector if possible.

**Comment by openback** [comment]
@pitbulk Thanks. I wasn't sure if this might be an issue with OneLogin itself or this library. I'm using a real connector, though, so I'll continue onward with them.
